Add resource attributes to the base template (for wb-main, wb-webpage, wb-publisher)
wet-boew/GCWeb pull request #1734
Opened 2020-10-12 02:45 UTC by ctopCanada

WET - 123 Add resource attributes to the base template (for wb-main, wb-webpage, wb-publisher)

2020-10-13 17:56 UTC, GormFrank requested changes
Also remove the changes on the release notes files (files that contain the word "release" in their name).

2020-10-13 17:56 UTC, GormFrank commented on site/pages/gcweb-theme/static-header-footer/bootstrap-3.html
> +
Remove empty line here.

2020-10-13 20:22 UTC, duboisp requested changes

2020-10-13 20:22 UTC, duboisp commented on site/pages/gcweb-theme/static-header-footer/bootstrap-3.html
> +<body vocab="http://schema.org/" resource="#wb-webpage" typeof="WebPage">
Missing a resource 
* at line 31 for the publisher info 
* at line 88 for the main element.

2020-10-13 20:22 UTC, duboisp commented on site/pages/gcweb-theme/static-header-footer/bootstrap-4.html
>  	<div id="wb-bnr" class="container">
Can you add the RDFa markup, like we have for the bootstrap 3 template, for the publisher area.
Here is line 35 to 40

2020-10-13 20:22 UTC, duboisp commented on site/layouts/splashpage.hbs
> +	<body class="{{pageclass}}" vocab="http://schema.org/" resource="#wb-webpage" typeof="WebPage">
Can you add the same RDFa attribute as the other page on the main element here at line 38

2020-10-13 20:22 UTC, duboisp commented on site/layouts/servermessage.hbs
> +				<div class="col-sm-6" property="publisher" resource="#wb-publisher" typeof="GovernmentOrganization">
Missing RDFa resource in the main element at line 25

2020-10-13 21:22 UTC, duboisp approved these changes

2020-10-15 17:34 UTC, duboisp commented
@ctopCanada please fix the linting error

2020-10-15 17:43 UTC, GormFrank requested changes

2020-10-15 17:43 UTC, GormFrank commented on site/layouts/splashpage.hbs
> +		<main role="main" property="mainContentOfPage" resource="#wb-main" typeof="WebPageElement" class="container">
Remove container class on this one:
```suggestion
		<main role="main" property="mainContentOfPage" resource="#wb-main" typeof="WebPageElement">
```

2020-10-22 17:57 UTC, GormFrank approved these changes

2020-10-22 17:58 UTC, duboisp submitted a review, later dismissed
@ctopCanada can you squash all the commits into 1 commits.

This was pre-approved, so after your squash we will be able to merged

2020-10-29 20:37 UTC, merged