JIRA ticket WET-143 (Panel headings are smaller than actual content inside its body)
wet-boew/GCWeb pull request #1759
Opened 2020-12-08 18:36 UTC by ctopCanada

Panel headings are smaller than actual content inside its body

2020-12-08 19:16 UTC, RobJohnston commented
You forgot to mention that this addresses https://github.com/wet-boew/GCWeb/issues/1726, I presume?

2020-12-08 19:24 UTC, GormFrank requested changes

2020-12-08 19:24 UTC, GormFrank commented on src/components/_base.scss
> +* Overwrite the font size as 1.2 em
```suggestion
* Panel title
```

2020-12-10 18:57 UTC, GormFrank approved these changes

2020-12-10 18:58 UTC, merged