Theme/topic: minor fixes
wet-boew/GCWeb pull request #1773
Opened 2021-01-27 15:32 UTC by GormFrank

**Including:**

- Background creating horizontal scroll on medium viewport;
- Removed unnecessary classes;
- Added inline fieldflow example;
- changed LinkedIn to true SVG.

2021-02-04 18:11 UTC, duboisp requested changes

2021-02-04 18:11 UTC, duboisp commented on site/pages/theme-topic-en.hbs
>  				<p>Summary of the information or tasks that can be accomplished on the sub-topic page. Remove prose or promotional messaging. Use action verbs.</p>
Please change the templated title in a way it suggested an action. At least for the description, like: Summary. Select a sub-category in the following drop down

2021-02-04 18:12 UTC, duboisp commented
Other than the small description change, it's look all good.

2021-02-05 20:31 UTC, duboisp approved these changes

2021-02-11 18:55 UTC, GormFrank commented on site/pages/theme-topic-en.hbs
>  				<h2 class="h3 mrgn-tp-md">Most requested</h2>
```suggestion
				<h2 class="h4 mrgn-tp-md">Most requested</h2>
```

2021-02-11 18:55 UTC, GormFrank commented on site/pages/theme-topic-en.hbs
>  		<h2>Services and information</h2>
```suggestion
		<h2>Services and information</h2>
```
```suggestion
		<h2 class="wb-inv">Services and information</h2>
```

2021-02-11 18:55 UTC, GormFrank commented on site/pages/theme-topic-en.hbs
>  				<h2 class="h3 mrgn-tp-md">Most requested</h2>
@delisma

2021-02-11 18:55 UTC, GormFrank commented on site/pages/theme-topic-en.hbs
>  		<h2>Services and information</h2>
@delisma

2021-02-11 19:01 UTC, merged