GC Subway: Fix accessibility issues
wet-boew/GCWeb pull request #1776
Opened 2021-02-05 19:33 UTC by GormFrank

This PR replaces the semantics for the decorative H1 on desktop from a paragraph to a div. It also adds a skip link to the first H1 which is dedicated to the subway.

Blocked by https://github.com/wet-boew/wet-boew/pull/9036

2021-02-05 20:20 UTC, duboisp requested changes

2021-02-05 20:20 UTC, duboisp commented on src/plugins/gc-subway/gc-subway.js
> +				skipLink = wb.addSkipLink( $h1.text, { name: "href", value: "#" + $h1.id } );
You will need to adjust this code based on the recent request change on the addSkipLink feature

2021-02-11 17:13 UTC, duboisp approved these changes

2021-02-11 19:32 UTC, GormFrank commented
We have to wait for GCWeb to use the latest version of WET once it is released.

2021-03-11 18:25 UTC, duboisp commented
@GormFrank please re-base and test your change.

If the update work, the skip link is added to the page, then we will be able to merge this PR and it is considered pre-approved at the technical review.

2021-03-15 17:09 UTC, duboisp approved these changes
I tested with the latest wet-boew and I made some little adjustment.

It's good to be merge now. @GormFrank can you review the code and let me know if you are ok with the small changes I mades?

2021-03-15 18:22 UTC, merged