Theme: Improve h1-h6 font size declarations
wet-boew/GCWeb pull request #1779
Opened 2021-02-09 22:23 UTC by EricDunsworth

* Replaces GCWeb's heading font size variables (``$h#-size``) with overrides for Bootstrap's ones (``$font-size-h#``)
* Removes redundant SCSS selectors (Bootstrap already has them)
* Uses pixel units to guarantee predictable font sizes:
  * Bootstrap and WET already use pixels
  * Ems can cause heading font sizes to deviate from their intended sizes if a parent element sets its own font size in ems
  * Might cause issues in pages that were misusing GCWeb's heading size classes to scale font sizes (i.e. ``.h1``, ``.h2``, etc...)

2021-02-09 22:28 UTC, EricDunsworth commented on src/views/_screen-sm-max.scss
> +	margin-top: 26px;
The expectations comment for the old ``margin-top`` property was way off... in practice Gecko and Blink were computing ``.75em`` to ``25.5px``. So I rounded it up to ``26px``.

2021-02-11 17:19 UTC, duboisp commented
Need to be tested and we need to ensure that the font-height exception for the header styling are kept. For example the gc-srvinfo

2021-02-11 19:40 UTC, duboisp commented
In what use case you need to use pixel?

2021-02-18 22:02 UTC, EricDunsworth commented
Just force-pushed an update to revert the pixel units back to ems.

@duboisp We've already spoken about my use case for using pixels, but just to put my stance in writing:

* Both Bootstrap 3.4.x and WET 4.0 use pixel units for their heading font sizes. Since GCWeb is a WET theme, I don't see any reason as to why it shouldn't also use pixels (aside from backwards compatibility with any code that intentionally misused the heading classes for font scaling).
* Font sizes that are based on pixel units are predictable. They'll always look the same size no matter what. By contrast, em-based font classes are open to being misused. It's possible to nest them together to scale the font size in ways that differ from what GCWeb intended. Take this super giant H5 for instance - that wouldn't be possible with pixel units:
  * ```<div class="h2"><div class="h2"><div class="h2"><div class="h2"><div class="h2"><div class="h2"><h5>H5</h5></div></div></div></div></div></div>```
* My down-to-earth use case was that I ran into a situation where I needed to place a heading within a ``<summary>`` element. That's not as simple as just throwing in a ``<h#>`` element. In order to make the summary's disclosure widget (triangle arrow) adopt the same font size as the heading, it's necessary to add a ``class="h#"`` attribute to the summary. But as a result of GCWeb's use of em units, ``<h#>`` grows way out of proportion since its font scales twice.

2021-02-25 18:42 UTC, GormFrank commented
Looks good, needs to be tested.

2021-04-08 17:16 UTC, GormFrank requested changes
Variables change look as expected.

Need to:

- [x] Rebase code

2021-04-15 17:04 UTC, EricDunsworth commented
Rebased :)!

2021-04-15 17:28 UTC, duboisp approved these changes

2021-04-15 17:29 UTC, merged