Repo reorg to support Méli-mélo, to run with Jekyll and CID with Github action
wet-boew/GCWeb pull request #1784
Opened 2021-02-18 07:53 UTC by duboisp

Une réorganisation complète du dépôt.

Ceci n'affecte pas les fonctionalités déjà supporté par l'API actuelle de GCWeb, La distribution finale de GCWeb JS/CSS est quasi identique à l'exception de l'ajout des contributions méli-mélo compilées et d'une réorgarnisation de l'assemblage. Les fichiers compilés avec l'aide des contribution méli-mélo sont seulement des fichiers JS/CSS pré-obsolètes et exclus de l'API de GCWeb. Ils sont ajouter à la distribution de GCWeb via son répertoire distinct nommé "méli-mélo" afin d'en facliter le deploiement.

En bref, ce PR va apporter les changment suivants:

* Adopte une structure orienté pour les éditeurs web qui utilise GCWeb
  * **components**: Contient l'ensemble des composants à utiliser dans le corps de la page
  * **sites**: Contient l'ensemble des composants pour le gabarit principal et le gabarit de base du thème de Canada.ca incluant les styles, l'en-tête, le pied de page communs.
  * **templates**: Contient les composants spécifique à des gabarits ainsi que les examples d'implémentation du sytème de conception de Canada.ca.
  * **docs**: Contenu web technique existant à propos de GCWeb.
* Utilisation du système d'hébergement web intégré de Github (Jekyll) pour la gestion de contenu du site web.
* Intégration et déploiement continue avec l'aide des Github Actions. Ceci inclus:
  * la validation préalable de la qualité du code
  * la compilation préalable pour le déploiement de production 
  * le déploiement continue de la distribution GCWeb
  * la mise à jour automatisé du thème GCWeb pour le système de gestion de contenu web Jekyll
* Ajout de la fonctionalité méli-mélo ce qui permettera au département d'ajouter du code JS et CSS personalisés selon quelques règles de base afin de faciliter la mise d'essaie rapide de nouvelle fonctionalité expérimentale sur Canada.ca sans toute fois compremettre la solution d'entreprise, GCWeb.
* Supporte la compilation et l'exécution entièrement locale à des fin de développement avec l'aide de Docker, Act et NodeJS (grunt)

2021-02-18 21:18 UTC, GormFrank reviewed
Ce fichier est inutile: components/gc-contributors/site-includes/version-1.hbs

Est-ce que c'est voulu d'avoir un text file dans le format odt? méli-mélo/@sample/working-in-progress-docs.odt 

Les images que tu enlèves (commencant par site/img/218x291.png), est-ce que c'est parce qu'elles ne sont pas utilisées?

Où sont les includes comme celui-ci maintenant? site/includes/most-requested.hbs

À quoi sert cette page? templates/home/api.html

2021-02-18 21:34 UTC, duboisp commented on package.json
> +  "version": "1.0.0",
J'ai indiqué la version 9.2.0 à titre indicatif à cause de l'ajout des fichiers méli-mélo. Mais en réalité, ce changement est seulement une patch. Les fichiers compilés méli-mélo sont et restera exclus de l'API publique de GCWeb.

Devrais-je le changé pour une incrémentation de correctif? Est-ce qu'on a fait des ajout mineur à GCWeb lors des deux dernières semaine?

2021-02-18 21:37 UTC, duboisp commented on docker-compose.yml
> +      - "4000:4000"
C'est indiqué dans la page d'index sous le sous-titre: "Run GCWeb website locally"

2021-02-18 21:38 UTC, duboisp commented on components/_triangle-up.scss
> +#triangle-up {
That code was already included in GCWeb. It probably used for the return at the top of the page or for something I am not aware of.

2021-02-18 22:07 UTC, duboisp commented
> Ce fichier est inutile: components/gc-contributors/site-includes/version-1.hbs

Effectivement et il doit être supprimé. 

> Est-ce que c'est voulu d'avoir un text file dans le format odt? méli-mélo/@sample/working-in-progress-docs.odt

Oui pour démontrer que divers documents peut être inclus avec le sous-projet de méli-mélo

> Les images que tu enlèves (commencant par site/img/218x291.png), est-ce que c'est parce qu'elles ne sont pas utilisées?

Oui effectivement, j'ai vérifié si les images étaient utilisé.

> Où sont les includes comme celui-ci maintenant? site/includes/most-requested.hbs

Il ont été retiré, leur contenu devrais être ajouté soit à même l'exemple pratique. Il faudrait l'ajouté dans le dossier _includes car ils sont seulement utilisé pour le contenu du site web.  

> À quoi sert cette page? templates/home/api.html

C'est une page technique qui décris l'API publique du gabarit de la page d'accueil.

2021-02-23 17:24 UTC, duboisp commented on package.json
> +    "ie > 10"
Just not touching it for now. I am fine to support it indirectly and we would remove it when switching to bootstrap 4 or 5 and WET 5.

2021-02-23 17:26 UTC, duboisp commented
Addition to consider
* [ ] Update the ci.yml to run when pushing to "patch*" branch and/or "developer"
* [ ] Fix typos in the act command line, like removing the repos and add the "s" before my_email

2021-02-23 21:13 UTC, GormFrank requested changes
Other than those typos (I'm sure there are more but we'll go back at some point), this PR covers a lot and I love the approach, we'll wait until we do one last release using the "old" folder structure and then adjust accordingly in order to be able to merge. We'll see how it goes afterwards once we start using the reorg in real life and we'll reassess what's been done if need be.

2021-03-16 21:24 UTC, duboisp commented on components/_base2.scss
> -	position: relative;
Yes, we can do it later.

2021-03-16 21:26 UTC, duboisp commented on components/wb-chtwzrd/_base.scss
> +	background: #fff url("../assets/wb-chtwzrd/default-avatar.png") center no-repeat;
On peut le noter dans la prochaine release.

2021-03-16 21:33 UTC, duboisp commented on Gruntfile.coffee
> +				packages = yepMeli.packages
I changed for `méliméloData`

2021-03-17 18:21 UTC, GormFrank approved these changes

2021-03-17 18:22 UTC, merged