Splash page - Update metadata
wet-boew/GCWeb pull request #1811
Opened 2021-05-05 15:54 UTC by Ricokola

Update metadata on Canada.ca splash page according to WET-150

2021-05-06 15:11 UTC, GormFrank requested changes

2021-05-06 15:11 UTC, GormFrank commented on templates/splash/layout-splashpage.html
>  		<meta content="width=device-width, initial-scale=1" name="viewport"/>
After further discussions and research, you would need to add the following reference to the Dublin Core namespace right under the `title` tag. What's important here is that it is included before your first instance of a `meta` with `dcterms`. No need for the `profile` attribute on the `head` which would be just for XHTML page and not for HTML.
 tag.
```suggestion
		<link rel="schema.dcterms" href="http://purl.org/dc/terms/" />
		<meta content="width=device-width, initial-scale=1" name="viewport"/>
```

2021-05-10 01:08 UTC, duboisp commented on templates/splash/splashpage.md
> +creator-fr: Service Canada
Change it for "Government of Canada", this splash page is not for Service Canada specifically.

2021-05-10 19:22 UTC, duboisp commented on templates/splash/splashpage.md
> +subject-fr: GV Gouvernement et vie politique;Services gouvernementaux
Here the controlled vocabulary used: https://canada.multites.net/cst/index.htm

2021-05-10 19:43 UTC, duboisp commented on templates/splash/layout-splashpage.html
> -		<meta content="width=device-width, initial-scale=1" name="viewport"/>
oh, it was moved 2 line below

2021-05-17 14:04 UTC, Ricokola commented on templates/splash/splashpage.md
> +subject-fr: GV Gouvernement et vie politique;Services gouvernementaux
This will need to be discussed for clarifications.

2021-05-20 17:45 UTC, duboisp requested changes
Pre-approved at the technical review after the second subject is removed,

2021-05-20 17:45 UTC, duboisp commented on templates/splash/splashpage.md
> +subject-fr: GV Gouvernement et vie politique;Services gouvernementaux
Can you remove the second subject "Government services"

2021-05-20 18:46 UTC, GormFrank approved these changes

2021-05-27 17:35 UTC, duboisp approved these changes

2021-05-27 17:35 UTC, merged