GC Checkboxes and radio - Plugin stabilization
wet-boew/GCWeb pull request #1817
Opened 2021-05-12 15:45 UTC by GormFrank

Related to WET-182

2021-05-12 20:11 UTC, duboisp requested changes
TODO: test it locally

2021-05-12 20:11 UTC, duboisp commented on components/gc-chckbxrdio/index.json-ld
> +		"examples": [
This shoudl be "docs" and the other "examples"

2021-05-12 23:44 UTC, delisma commented
> Related to WET-182

Can we be a bit more detailed about WET-182?

2021-05-13 12:40 UTC, GormFrank commented
@Delisma WET-182 is the ticket number of our internal request, which about stabilizing the Checkboxes and radio buttons pattern and then applying that pattern to Field flow. I didn't think there was any description needed for this PR since the title describes it enough. PR for implementation with Field flow will come soon. There you go I'll add that.

2021-05-13 17:24 UTC, duboisp reviewed
Approved after local test and wait for the implementation of the GC Checkboxes in field flow

2021-06-01 03:08 UTC, duboisp commented
@GormFrank please resolve conflict

2021-06-01 03:23 UTC, duboisp commented on components/gc-chckbxrdio/gc-chckbxrdio-doc-en.html
> +	<dd>Content and IA spec 2.1</dd>
This is not defined by the content and IA spec, but just by the "Template and design pattern library" which is not versioned currently.

2021-06-01 03:23 UTC, duboisp commented on components/gc-chckbxrdio/index.json-ld
> +		"examples": [
Can you add the reference to the design system, like how it is added in the legislation pages

2021-06-01 03:23 UTC, duboisp commented on components/provisional-fr.html
> +			<td>Stable</td>
Add the date or the next expected version number of GCWeb (Minor)

2021-06-01 19:50 UTC, duboisp commented on components/gc-chckbxrdio/gc-chckbxrdio-doc-en.html
> +parentdir: components
This is not needed

2021-06-02 02:18 UTC, duboisp requested changes
There is a small glitch with the inline checkbox and inline radio button

![1px checkbox](https://user-images.githubusercontent.com/1676030/120413905-1cd82400-c327-11eb-8581-6a56bf8c0b7f.PNG)
![1px checkbox-checked](https://user-images.githubusercontent.com/1676030/120413907-1cd82400-c327-11eb-8d9c-e329069070d5.PNG)
![1px radio](https://user-images.githubusercontent.com/1676030/120413908-1cd82400-c327-11eb-9418-f61e65fa3dda.PNG)

I will check what I can do to fix that issue.

There is also unnecessary `class="disable"` code. I going to include that change too.

2021-06-02 02:34 UTC, duboisp requested changes
We would need to replace the class `chckbxrdio-grp` because it is associated to no style. However, I think the intend was to use this style : `chkbxrdio-grp` (without "c" as the third character)

2021-06-02 04:33 UTC, duboisp requested changes
The HTML markup in the working example are not conform to WCAG. More particularly the information and relationship because some content don't belong to their parent heading and some section are identified with multiple top level heading.

Note: I am going to submit a change to fix that.

2021-06-02 04:52 UTC, duboisp approved these changes
Approved,
I applied the required changes and I fixes the checkbox/radio display issue when it was displayed inline
I successfully tested locally and did a partial WCAG assessment only on how the checkboxes/radio are implemented and checked the HTML pages structure.

2021-06-02 12:10 UTC, GormFrank commented
> The HTML markup in the working example are not conform to WCAG. More particularly the information and relationship because some content don't belong to their parent heading and some section are identified with multiple top level heading.
> 
> Note: I am going to submit a change to fix that.

@duboisp Can you be more specific in this review? I did not change the semantic of the page from the provisional one so I don't have a reference on what you are pointing out now that you have pushed the changes. Just want to see how obvious it was. Thanks!

2021-06-02 12:14 UTC, GormFrank commented
> We would need to replace the class `chckbxrdio-grp` because it is associated to no style. However, I think the intend was to use this style : `chkbxrdio-grp` (without "c" as the third character)

@duboisp Yes, the intent is to use the one without the "c", which I thought I did a Find and replace everywhere. The typo dates back to when it was in provisional state.

2021-06-02 12:15 UTC, GormFrank commented
> There is a small glitch with the inline checkbox and inline radio button

@duboisp I am not sure I understand what the glitch is/was from those screenshots. I'm testing your change now.

2021-06-02 12:26 UTC, GormFrank reviewed
> There is a small glitch with the inline checkbox and inline radio button

What browser were you using? I never encountered this glitch. Your quick change fixes it though 🥇

2021-06-02 12:26 UTC, GormFrank commented on components/gc-chckbxrdio/_base.scss
> +
@duboisp You decided to include the `chkbxrio-grp` styles so that we don't need to use the helper? Good idea.

2021-06-02 12:29 UTC, GormFrank commented
@duboisp I'm just asking myself if it is necessary to repeat "with explicit label" on every single `<h2>` on the page. Everything looks good now though.

2021-06-02 14:36 UTC, duboisp approved these changes

2021-06-02 14:37 UTC, merged

2021-06-08 03:03 UTC, duboisp commented
Just find out that the provisional code for the checkbox was not removed from the provisional CSS, like here: https://github.com/wet-boew/GCWeb/blob/master/components/_provisional.scss#L158