GC tables: Remove datatables' bottom table border
wet-boew/GCWeb pull request #1842
Opened 2021-06-04 21:21 UTC by EricDunsworth

A bottom table border used to appear in small view and under when pairing GC tables alongside WET's datatables plugin.

This removes that border when GC tables' styles are in effect.

Note:
I also wanted to make GC tables disable datatables' optional scrolling features, but was unable to since its scrolling container is situated outside the table.

**Screenshots...**

**Before:**
![gc-tables-datatables-before](https://user-images.githubusercontent.com/1907279/120863824-42e50a80-c559-11eb-9277-7c798f8141f0.png)

**After:**
![gc-tables-datatables-after](https://user-images.githubusercontent.com/1907279/120863827-44aece00-c559-11eb-8588-08e867f55a34.png)

**PS:**
This will need to be rebased after #1841 gets merged.

2021-06-05 03:08 UTC, duboisp requested changes
@EricDunsworth We would need a working example. What is your context of use of the dataTable plugin along with the gc-table. If it is only for the filtering feature, you can use the filter plugin which don't impact the table layout.  

@delisma @jmealing any concern?

2021-06-08 14:58 UTC, EricDunsworth commented
The goal of this PR is to allow an implementer to use the best of both worlds so to speak:
* Datatables-specific features (like column sorting) in tables that are presented using tabular layouts in medium view and over.
* Linearized tables in small view and under (i.e. making them more mobile-friendly than they'd otherwise be).
* Taking advantage of datatables-specific features that can lend themselves to all views (e.g. filtering, pagination, etc...).

Datatables already has optional [configuration options for responsive tables](https://datatables.net/extensions/responsive/) (see  the example on [datatables' landing page](https://datatables.net/)). But that works very differently from GC tables:
* Responsive datatables work by hiding columns that can't fit on-screen. Visible data cells turn into interactive controls that can show/hide the hidden column data.
* GC tables works by hiding table headers (``<thead>``), linearizing all table rows and presenting them like "mini tables". It also uses pure CSS.

So given all that... some implementers might prefer the way GC tables presents table data in smaller views over responsive datatables. So I don't see any harm in giving them the option to use it. Especially since it barely needs any additional CSS.

Btw this PR won't make all datatables implementations perfectly compatible with GC tables. But it should cover most use cases. The only scenarios I can think of off hand where it wouldn't work very elegantly would be if the [table is scrollable](https://datatables.net/examples/basic_init/scroll_y.html) or if the [table is already responsive](https://datatables.net/extensions/responsive/).

@duboisp I hadn't considered using the filter plugin alongside a normal GC tables implementation. But IMO datatables still has enough going for it that it'd make sense to support.

2021-06-08 18:21 UTC, jmealing commented
All good - I haven't noticed that dark line border appearing in my testing. Thank you for removing it Eric

2021-06-09 14:43 UTC, duboisp commented
TODO:
* [ ] Create a working example with the data table plugin

2021-06-15 18:46 UTC, duboisp approved these changes

2021-06-16 14:21 UTC, duboisp commented
pre-approved upon conflict resolved

2021-06-16 14:33 UTC, duboisp approved these changes

2021-06-16 14:34 UTC, merged