GC tables: Space-out adjacent tbody separator borders
wet-boew/GCWeb pull request #1846
Opened 2021-06-08 17:12 UTC by EricDunsworth

Bootstrap's "tables" class adds a 2px border between adjacent ``tbody`` elements.

But it looked out of place in GC tables. That component adds a bottom margin to every row... which caused the adjacent ``tbody``'s top border to look like it was "sticking" to its first row.

This resolves it by adding a top margin to the adjacent ``tbody``'s first row to prevent the sticking. That allows the top border to look like a real separator.

Spinoff of #1843.

**Screenshots...**

**Before:**
![gc-tables-tbody-adjacent-before](https://user-images.githubusercontent.com/1907279/121228409-b7ba8c00-c85a-11eb-8a49-7381ef689461.png)

**After:**
![gc-tables-tbody-adjacent-after](https://user-images.githubusercontent.com/1907279/121228414-b8ebb900-c85a-11eb-8b09-42f2164f6239.png)

CC @jmealing @delisma @duboisp

2021-06-09 14:47 UTC, duboisp commented
We will need a working example.

@delisma @jmealing what do you think of this style?

2021-06-09 14:47 UTC, duboisp requested changes
Need a working example

2021-06-09 15:11 UTC, jmealing commented
@duboisp What do we need a working example of? Wouldn't this correction be the default because the examples use the class "table"? 

The correction to fix the overlapped border looks good to me, thank you @EricDunsworth

2021-06-09 20:30 UTC, EricDunsworth commented
I've just added a second ``tbody`` into the first example to demonstrate adjacent ones. IMO it didn't warrant its own distinct example given that there's nothing very special about using multiple tbody elements (it's standard HTML markup).

2021-06-15 18:47 UTC, duboisp approved these changes

2021-06-16 14:21 UTC, duboisp commented
pre-approved upon conflict resolved

2021-06-16 14:44 UTC, duboisp approved these changes

2021-06-16 14:44 UTC, merged