GCWeb Home page: update home and index pages
wet-boew/GCWeb pull request #1848
Opened 2021-06-08 20:09 UTC by Ricokola

2021-06-09 12:09 UTC, duboisp requested changes
All your changes look great.

I forget to mention, can you change the link in the splash page too (index.html)

2021-06-09 14:40 UTC, Ricokola commented
> 
> 
> All your changes look great.
> 
> I forget to mention, can you change the link in the splash page too (index.html)

@duboisp links on the index page have been updated.

2021-06-09 14:51 UTC, duboisp commented
@Ricokola can you resolve the merge conflict? Thanks

2021-06-09 14:51 UTC, duboisp approved these changes

2021-06-10 13:51 UTC, duboisp approved these changes

2021-06-14 16:59 UTC, duboisp approved these changes

2021-06-14 16:59 UTC, merged