Features - Apply well, move link title below the image and adjust one tile feature
wet-boew/GCWeb pull request #1870
Opened 2021-07-12 17:36 UTC by Ricokola

Related: WET-183
Blocked by: #1866

2021-07-14 19:00 UTC, GormFrank requested changes

2021-07-15 13:44 UTC, GormFrank approved these changes

2021-07-21 11:34 UTC, Ricokola commented
@GormFrank text-decoration and version # adjusted...now ready for final review.

2021-07-21 17:30 UTC, GormFrank approved these changes

2021-07-28 15:18 UTC, GormFrank approved these changes
Pre-approved provided ther eis no bakcward compatibility issue.

2021-08-13 15:07 UTC, merged