wet-195 Ministerial-profile GCWeb template updates
wet-boew/GCWeb pull request #1884
Opened 2021-09-16 12:28 UTC by Ricokola

2021-09-16 14:49 UTC, GormFrank requested changes
@Ricokola Few changes and can you please include the "Share this page" button at the bottom of the page?

2021-09-16 14:49 UTC, GormFrank commented on templates/ministerial/ministerial-doc-en.html
> +	<dd><a href="https://design.canada.ca/mandatory-templates/ministerial-profile-pages.html">Ministerial profile pages - Canada.ca mandatory template</a></dd>
At the moment, the right link to specifications page ends with a "-draft", like so:
```suggestion
	<dd><a href="https://design.canada.ca/mandatory-templates/ministerial-profile-pages-draft.html">Ministerial profile pages - Canada.ca mandatory template</a></dd>
```

2021-09-16 14:49 UTC, GormFrank commented on templates/ministerial/ministerial-doc-en.html
> +</ul>
Add an H3 before the list mentioning: "Version 2.0", and then an H3 after the list mentioning: "Version 1.0" followed by a single bullet list mentioning: "Initial template", something like so:
```suggestion
<h3>Version 2.0</h3>
<ul>
	<li>replaced Latest, Recent announcements, and Gallery with a flexible Features section </li>
	<li>removed the social media feed and added an optional Follow me section instead</li>
	<li>simplified and streamlined the guidance </li>
	<li>clarified how to display ministers, parliamentary secretaries and heads of organizations</li>
</ul>
<h3>Version 1.0</h3>
<ul>
	<li>Initial template</li>
</ul>
```

2021-09-16 14:49 UTC, GormFrank commented on templates/ministerial/ministerial-en.html
>  <div class="row">
Please remove this wrapping div (and don't forget its closing tag), it makes the content overflow on both sides.
```suggestion

```

2021-09-16 17:30 UTC, GormFrank requested changes
One change remaining, please do the same in French. I'd say that "Change history" should translate to "Historique des changements".

2021-09-16 17:30 UTC, GormFrank commented on templates/ministerial/ministerial-doc-en.html
> +</ul>
This shoud be the outcome, and maybe it is clearer if you replace "Recent hanges" by "Change history":
```suggestion
<ul>
	<li><a href="ministerial-en.html">Working example</a></li>
	<li><a href="ministerial-fr.html" lang="fr">Exemple pratique</a></li>
</ul>

<h2>Change history</h2>

<h3>Version 2.0</h3>
<ul>
	<li>replaced Latest, Recent announcements, and Gallery with a flexible Features section </li>
	<li>removed the social media feed and added an optional Follow me section instead</li>
	<li>simplified and streamlined the guidance </li>
	<li>clarified how to display ministers, parliamentary secretaries and heads of organizations</li>
</ul>

<h3>Version 1.0</h3>
<ul>
	<li>Initial template</li>
</ul>
```

2021-09-16 19:50 UTC, GormFrank requested changes
Last changes to the front matter and please include the following [built _data/templates.json file](https://gormanproductions.ca/wet/labs/pr1884/templates.json) to this PR, then it'll be good to go! :)

2021-09-16 19:50 UTC, GormFrank commented on templates/ministerial/ministerial-doc-en.html
> +altLangPage: ministerial-fr.html
```suggestion
altLangPage: ministerial-doc-fr.html
```

2021-09-16 19:50 UTC, GormFrank commented on templates/ministerial/ministerial-doc-fr.html
> +language: en
```suggestion
language: fr
```

2021-09-16 19:50 UTC, GormFrank commented on templates/ministerial/ministerial-doc-fr.html
> +altLangPage: ministerial-fr.html
```suggestion
altLangPage: ministerial-doc-en.html
```

2021-09-17 12:07 UTC, GormFrank approved these changes
@duboisp Take a look if you wish, but I believe we are good to go! This has to be merged today :)

2021-09-17 18:31 UTC, duboisp approved these changes
@GormFrank I am going to approve considering we need this template to be compatible with v9.4.1 of GCWeb because that is the version currently deployed on Canada.ca. 

We would need to review this template and make it more modular where the component code are taken directly from component working space instead of being duplicated here. @Ricokola I would help you to do that.

The documentation would need to be reviewed and all the component in this template would need to be clearly identify.

2021-09-17 18:31 UTC, duboisp commented on templates/ministerial/ministerial-en.html
> +<section class="gc-features">
Please use the latest pattern for "gc-features", Although I understand we need this page template to work with v9.4.1 of GCWeb.

2021-09-17 19:01 UTC, merged