Reduced Ministerial profiles - Addition of Parliamentary Secretaries
wet-boew/GCWeb pull request #1910
Opened 2021-11-25 19:15 UTC by Ricokola

Related to: WET-210

Addition of new design pattern for reduced Parliamentary Secretaries profiles to the reduced Ministerial profile pages template.

2021-11-30 03:14 UTC, GormFrank commented
@Ricokola Looks good but asked business analyst for clarifications on the “Represents the riding of [Riding name]” paragraph to know if it should be there or not for the Parliamentary Secretaries version.

2021-12-01 11:44 UTC, Ricokola commented
> @Ricokola Looks good but asked business analyst for clarifications on the “Represents the riding of [Riding name]” paragraph to know if it should be there or not for the Parliamentary Secretaries version.

@GormFrank it has been confirmed that the “Represents the riding of [Riding name]” should not be there for the Parliamentary Secretaries version. Therefore, I have added an info label beside the [Riding name] paragraph mentioning "Ministerial profil only".

2021-12-01 14:16 UTC, GormFrank approved these changes

2021-12-01 20:01 UTC, duboisp requested changes
I suggest to duplicate the page and remove the use of the label

2021-12-02 20:10 UTC, duboisp approved these changes

2021-12-02 20:12 UTC, merged