Revamp of the index page
wet-boew/GCWeb pull request #1914
Opened 2021-12-04 02:48 UTC by GormFrank

Total revamp of the index page to improve UI/UX on both Mobile and Desktop and make it look a little bit like the [WET-BOEW style guide](https://wet-boew.github.io/wet-boew-styleguide/index-en.html).

2021-12-08 20:09 UTC, duboisp requested changes

2021-12-08 20:09 UTC, duboisp commented on index-en.md
> +<div class="container-fluid wb-inview show-none bar-demo" data-inview="nav-menu">
`bar-demo` ????

2021-12-08 20:09 UTC, duboisp commented on index-fr.md
> +<div class="container-fluid wb-inview show-none bar-demo" data-inview="nav-menu">
`bar-demo` ?

2021-12-08 20:09 UTC, duboisp commented on index-fr.md
> +	</ul>
Broken anchor

2021-12-08 20:41 UTC, GormFrank commented on index-fr.md
> +<div class="container-fluid wb-inview show-none bar-demo" data-inview="nav-menu">
Oh lol copy and paste artifacts :-P

2021-12-22 19:19 UTC, duboisp approved these changes
Thats is great.

Thanks @GormFrank

2021-12-22 19:20 UTC, merged