SR-109: Add data-fusion-query to search templates
wet-boew/GCWeb pull request #1954
Opened 2022-03-23 14:57 UTC by igkislev

2022-03-25 19:01 UTC, duboisp requested changes
Please documents this change.

Add a version bullet here: https://github.com/wet-boew/GCWeb/blob/master/templates/search/api.html#L66

This is a minor template change.

Document the code addition in the section "Template - Search bar", "Template - Search bar contextual" and "Template -Alternate 'Search bar' "

Add the new code sample and archive the current one into a details/summary like the following

```html
<pre><code>
... The updated html here with data-fusion-query ...
</code></pre>
<details>
   <summary>as per version 2.1</summary>
<pre><code>
... The html that was already documented in the page ...
</code></pre>
</details>
```

2022-03-30 05:37 UTC, duboisp requested changes

2022-03-30 05:37 UTC, duboisp commented on templates/search/results-contextual-en.html
> +		<input class="form-control full-width" spellcheck="false" autocomplete="off" dir="ltr" id="sch-inp" name="q" type="search" data-fusion-query="safe" />
@igkislev can you remove the value "safe"? That parameter value have no effect.
```suggestion
		<input class="form-control full-width" spellcheck="false" autocomplete="off" dir="ltr" id="sch-inp" name="q" type="search" data-fusion-query />
```

2022-03-30 05:37 UTC, duboisp commented on templates/search/results-en.html
> +		<input spellcheck="false" autocomplete="off" id="sch-inp" class="form-control" type="search" data-fusion-query="safe"  name="q" />
```suggestion
		<input spellcheck="false" autocomplete="off" id="sch-inp" class="form-control" type="search" data-fusion-query  name="q" />
```

2022-03-30 05:37 UTC, duboisp commented on templates/search/results-fr.html
> +		<input spellcheck="false" autocomplete="off" id="sch-inp" class="form-control" type="search" data-fusion-query="safe" name="q" />
```suggestion
		<input spellcheck="false" autocomplete="off" id="sch-inp" class="form-control" type="search" data-fusion-query name="q" />
```

2022-04-06 18:22 UTC, duboisp requested changes
@igkislev 

* [ ] Please documents this change.
* [ ] Add a version bullet here: https://github.com/wet-boew/GCWeb/blob/master/templates/search/api.html#L66
* [ ] Document the code addition in the section "Template - Search bar", "Template - Search bar contextual" and "Template -Alternate 'Search bar' "
* [ ] Add the new code sample and archive the current code

2022-04-06 18:27 UTC, GormFrank requested changes

2022-04-06 18:27 UTC, GormFrank commented on templates/search/results-en.html
> +		<input spellcheck="false" autocomplete="off" id="sch-inp" class="form-control" type="search" data-fusion-query  name="q" />
Suuuuper small request. Can you please remove one space just for the purpose of having consistent clean code? Not an error, I<m just really picky sometimes 😛 

```suggestion
		<input spellcheck="false" autocomplete="off" id="sch-inp" class="form-control" type="search" data-fusion-query name="q" />
```

2022-04-13 18:14 UTC, duboisp commented
Approved after the automated build is completed and after a quick local testing to see how the change made are displayed.

2022-04-22 12:49 UTC, GormFrank requested changes
Apart from those small changes requested, the rest looks good. Thank you @igkislev!

2022-05-13 14:33 UTC, GormFrank requested changes

2022-05-13 14:58 UTC, GormFrank approved these changes

2022-05-13 16:23 UTC, GormFrank requested changes

2022-05-13 16:23 UTC, GormFrank commented on templates/search/results-contextual-fr.html
> +
@igkislev This one is still an issue, and it is the last one it seems. You need to remove the empty spaces / tab.

2022-05-13 18:05 UTC, GormFrank approved these changes

2022-06-02 19:08 UTC, duboisp approved these changes

2022-06-02 19:08 UTC, merged