Thematic update for Canada Day
wet-boew/GCWeb pull request #1967
Opened 2022-05-04 18:19 UTC by nfrenette

Updated red hex and added beige CSS and examples

2022-05-04 18:34 UTC, GormFrank commented
Pre-approved during technical review upon successful testing. (NEED TO SQUASH AND MERGE)

2022-05-04 18:34 UTC, duboisp requested changes
All CSS need to be demoed.

2022-05-04 18:34 UTC, duboisp commented on méli-mélo/th-canadaday/style.css
> +body .bg-canadaday-beige {
Need a demo or be removed.

With gcweb-jekyll I do think you can use the front-matter "pageclass" like our pink-day working example demo

2022-05-05 11:22 UTC, duboisp approved these changes
All examples are demoed, documented and will nicely fallback according to the progressive enhancement design principle.

My few change request is to improve the anchor working example. An anchor should not have the role button when it is not acting as a button.  Also, when a role is available in the host language, we should use the host language before to override it with ARIA.

I know that you have enforced the text-white on link to avoid the little blue but I remarked the button still show the little blue on mouse hover.

2022-05-05 11:22 UTC, duboisp commented on méli-mélo/th-canadaday/canada-day.html
> +    <a href="#" class="btn btn-info bg-canadaday text-white" role="button">Button</a>
```suggestion
    <a href="#" class="btn btn-info bg-canadaday text-white">Anchor</a>
```

2022-05-05 11:22 UTC, duboisp commented on méli-mélo/th-canadaday/canada-day.html
> +    <pre><code>&lt;a href="#" class="btn btn-info bg-canadaday text-white" role="button"&gt;Button&lt;/a&gt;</code></pre>
```suggestion
    <pre><code>&lt;a href="#" class="btn btn-info bg-canadaday text-white"&gt;Anchor&lt;/a&gt;</code></pre>
```

2022-05-05 11:22 UTC, duboisp commented on méli-mélo/th-canadaday/canada-day.html
> +    <a href="#" class="btn btn-default bg-canadaday-beige" role="button">Button</a>
```suggestion
    <a href="#" class="btn btn-default bg-canadaday-beige">Anchor</a>
```

2022-05-05 11:22 UTC, duboisp commented on méli-mélo/th-canadaday/canada-day.html
> +    <pre><code>&lt;a href="#" class="btn btn-default bg-canadaday-beige" role="button"&gt;Button&lt;/a&gt;</code></pre>
```suggestion
    <pre><code>&lt;a href="#" class="btn btn-default bg-canadaday-beige"&gt;Anchor&lt;/a&gt;</code></pre>      
```

2022-05-05 11:23 UTC, merged