Update Menu to v3.0 to make column consistent even with authentication
wet-boew/GCWeb pull request #1977
Opened 2022-05-25 13:44 UTC by Ricokola

Related to: WET-248

- Adjust column from 12 to 8 to the Header where the GCWeb Menu is to be consistent whether there is an Authentication section or not.
- Adjust and enhance the Header documentation to reflect changes and to update to version 3.0.
- Enhancement of the GCWeb documentation (Content change only).
- Update `col-xs-offset-7 col-xs-5` by `col-xs-offset-6 col-xs-6`

2022-06-01 18:33 UTC, duboisp requested changes
The home page template still use the `col-sm-12`, please update that working example

2022-06-03 11:35 UTC, Ricokola commented
@duboisp ready to be reviewed

2022-06-08 00:46 UTC, duboisp commented on sites/header/deprecated/home-v2.html
> +							<div class="col-md-12">
This layout need to be updated. That is where I found the reference to col-sm-12. https://github.com/wet-boew/GCWeb/blob/master/templates/home/layouts/home.html#L42

2022-06-08 18:59 UTC, Ricokola commented
@duboisp sites/header/deprecated/home-v2.html has been updated as suggested and the PR is now ready for review.

2022-06-15 18:09 UTC, duboisp requested changes
This file need to be updated too: https://github.com/wet-boew/GCWeb/blob/master/templates/home/layouts/home.html

+ Add some little migration instruction

2022-06-29 17:50 UTC, duboisp commented
* [ ] Please add a small description of the change that happen on the home page template in the home page documentation page
* [ ] For the home page template, I do think we can directly use the header include instead of duplicating the logic.
* [ ] Add a section in the home page documentation where it list all production instance of the home page. Basically the EN and FR page on Canada.ca

When that is completed, we will be good to merge

2022-08-29 16:35 UTC, GormFrank requested changes
@Ricokola super travail :)

Tant qu'à modifier les colonne de header, aussi bien par le fait même améliorer la colonne pour le sign in button en mobile; c'est-à-dire de changer `col-xs-offset-7 col-xs-5` par `col-xs-offset-6 col-xs-6` (ne pas oublié d'ajouter cette référence dans le CSS pour garder le margin-top négatif et garder l'ancienne référence aussi pour ne pas causer de major). C'est seulement pour ne pas que le bouton tombe sur deux lignes sur téléphone mobile.

2022-08-29 16:35 UTC, GormFrank commented on sites/header/header-docs-en.html
> +<h2>Before and After</h2>
Je mettrais le titre "Before and After" en tant que H3 en-dessous d'un nouveau H2 nommé "Template". De ce fait, le titre "Previous versions" doit aussi devenir un H3 toujours sous le "Template", puis "Working examples" deviendra un H4. (Faire de même pour le Français)

2022-08-29 16:35 UTC, GormFrank commented on templates/home/api-fr.html
> +<h3 id="home-page-banner">Home page header</h3>
typo
```suggestion
<h3 id="home-page-header">Home page header</h3>
```

2022-08-29 16:35 UTC, GormFrank commented on templates/home/api-fr.html
> +	<li><a href="#home-page-header">Home page header</a> - Version 2.0</li>
typo
```suggestion
	<li><a href="#home-page-header">Home page header</a> - Version 3.0</li>
```

2022-08-29 16:35 UTC, GormFrank commented on templates/home/api-en.html
> +<h3 id="home-page-banner">Home page header</h3>
typo
```suggestion
<h3 id="home-page-header">Home page header</h3>
```

2022-08-29 16:35 UTC, GormFrank commented on templates/home/api-en.html
> +	<dd>https://www.canada.ca/en.html</dd>
Should be links <a> and in the same <dd> element (could be separated by a comma "," or the word "and").

2022-08-29 16:35 UTC, GormFrank commented on templates/home/layouts/home.html
> +		{% include header/header.html %}
The home page must not have a breadcrumb.

2022-10-05 18:09 UTC, duboisp reviewed
* [ ] Review and local testing

pre-approved at the technical review.

2022-10-06 05:15 UTC, duboisp requested changes
* [ ] Keep all deprecated "home" template at the same place, within the template home and not with the sites header. (4 files to moves)

---

Question:
Only for the home page - The working example for the version 3 of the structural don't match the changes described in the documentation. Is that intentional or not? I know that at one point our home page didn't followed the update on our generic pages.

2022-10-06 05:15 UTC, duboisp commented on sites/header/header-docs-fr.html
> +</ul>
Please put those link in a "details/summary" element like you did in English.

2022-10-12 18:23 UTC, duboisp commented
pre-approved upon successful local testing + code review

2022-10-19 15:41 UTC, duboisp requested changes
I review and tested. There is one little additional change and the rest look good.

* [ ] Fail SC 3.1.2 Language of part for the "header-docs-fr.html"

2022-10-19 15:41 UTC, duboisp commented on sites/header/header-docs-fr.html
> +</details>
A traduire ou ajouter le language tag et une note disant que quelques partie de ce document nécessite une traduction.

2022-10-20 14:11 UTC, duboisp approved these changes

2022-10-24 14:43 UTC, duboisp commented
@Ricokola or @GormFrank could one of you resolve the merge conflict. Thanks

FYI - The conflict files are:
* sites/authentication/authentication-en.html
* sites/authentication/authentication-fr.html

Pre-approved once the conflict is resolve and the change is only about the above file

2022-10-24 16:40 UTC, GormFrank commented
@duboisp Rebased!

2022-10-25 01:48 UTC, duboisp approved these changes
Change requested was made and I reviewed and tested the last modified file since my last review and it works as expected.

2022-10-25 01:53 UTC, merged