Documentation: Changing index page global elements listing layout
wet-boew/GCWeb pull request #2010
Opened 2022-09-09 14:02 UTC by Garneauma

Layout of Sites and global functionality changed to match Templates and Components layout.

2022-09-13 12:29 UTC, Ricokola approved these changes

2022-09-14 18:39 UTC, duboisp requested changes
Good to go after the 2 little typo.

2022-09-14 18:39 UTC, duboisp commented on index-en.md
> +	<ul class="row list-unstyled wb-eqht-grd wb-filter mrgn-tp-md"data-wb-filter='{ "selector": ">li" }'>
```suggestion
	<ul class="row list-unstyled wb-eqht-grd wb-filter mrgn-tp-md" data-wb-filter='{ "selector": ">li" }'>
```

2022-09-14 18:39 UTC, duboisp commented on index-fr.md
> +	<ul class="row list-unstyled wb-eqht wb-filter mrgn-tp-md"data-wb-filter='{ "selector": ">li" }'>
```suggestion
	<ul class="row list-unstyled wb-eqht wb-filter mrgn-tp-md" data-wb-filter='{ "selector": ">li" }'>
```

2022-09-14 19:11 UTC, Garneauma commented
> Good to go after the 2 little typo.

C'est fait :)

2022-09-21 18:22 UTC, duboisp approved these changes

2022-09-21 18:22 UTC, merged