GCWeb theme implementing guide - Create French version
wet-boew/GCWeb pull request #2011
Opened 2022-09-09 18:41 UTC by Ricokola

Related to: WET-268

2022-09-09 20:01 UTC, GormFrank reviewed
@Ricokola Pour éviter le changement de nom de fichier, je viens d'avoir une idée. On pourrait laisser la page anglaise nommée "implementing", puis nommer la française "implementer"?

CC: @duboisp

2022-09-14 18:44 UTC, duboisp requested changes
Add a meta-redirect for "implementing.html" and add a comment "Temporary redirect until September 2023"

See this page as an example: https://github.com/wet-boew/themes-dist/blob/f0a0d8ef08cd50840676e96cf0caff29c124a645/demos/index-en.html

2022-09-14 18:45 UTC, duboisp commented
Otherwise the redirect page, this PR look good to be merged.

2022-09-14 19:49 UTC, Ricokola commented
@duboisp and @GormFrank the redirect page has been created. Please review and merge if everything is good!

2022-09-21 18:25 UTC, duboisp requested changes
Other than the new line feed. it looks good to merge.

This is a Content change only

2022-09-21 18:25 UTC, duboisp commented on docs/implementing.html
> +</html>
Need a new line here

2022-09-21 19:19 UTC, duboisp approved these changes
Requested change was applied.

2022-09-21 19:20 UTC, merged