Build warnings: includes, byline and more
wet-boew/GCWeb pull request #2087
Opened 2023-01-19 15:29 UTC by Garneauma

Resolving build warnings part 4:
- Fixing byline file include which did not recognize "i18nText-lang"
- Fixing syntax for byline include call
- Integrating "comp-download" include content directly in files calling it (2 files)
- Integrating "minister-port" include content directly in files calling it (2 files)
- Integrating "fullmenu" include content directly in files calling it (2 files)
- Integrating "placeholder-content" include content directly in files calling it (2 files)
- Integrating "carousel-small" include content directly in files calling it (2 files)

2023-01-23 15:12 UTC, Ricokola commented
Pre-approved upon successful testing

2023-01-24 04:48 UTC, duboisp requested changes
Other than the heading text that are not matching for the old mega menu, the rest which I tested and reviewed look good.

2023-01-24 04:48 UTC, duboisp commented on sites/gcweb-menu/ajax/sitemenu-fr.hbs
> +	<h2 class="wb-inv">Sujets</h2>
I did found "Menu des sujets"

ref. https://github.com/wet-boew/themes-dist/blob/v9.0.0-gcweb/ajax/sitemenu-fr.html#L8

2023-01-24 04:48 UTC, duboisp commented on sites/gcweb-menu/ajax/sitemenu-en.hbs
> +	<h2 class="wb-inv">Topics</h2>
I did found "Topics menu"

ref: https://github.com/wet-boew/themes-dist/blob/v9.0.0-gcweb/ajax/sitemenu-en.html#LL8C20-L8C34

2023-01-24 13:33 UTC, Garneauma commented
> Other than the heading text that are not matching for the old mega menu, the rest which I tested and reviewed look good.

The headings have been updated. :)

2023-02-01 05:19 UTC, duboisp approved these changes
Completed the review + local testing. And the requested change was completed as expected.

2023-02-06 15:18 UTC, merged