Build warnings: contact us, corp info, supportedby
wet-boew/GCWeb pull request #2090
Opened 2023-01-20 18:17 UTC by Garneauma

Resolving build warnings part 7:
- Adding institutional information include file
- Adding organizational information include file
- Fixing reference to institutional info include file
- Fixing reference to organizational info include file
- Integrating "supported-by" include file content into files calling it

2023-01-23 15:11 UTC, Ricokola commented
Pre-approved upon successful testing

2023-01-24 05:26 UTC, duboisp requested changes
* [ ] Code sample should be in the "samples" folder instead of "includes"
* [ ] Move `gc-crprt` as a components outside templates

2023-01-24 05:26 UTC, duboisp commented on templates/institutional/includes/inst-info.html
> +<section class="gc-crprt">
Would this code sample be in the "components" under "gc-crprt". It look very similar to the other code sample in organisation template.

I suggest to put both content sample under "components/gc-crprt/samples/" folder

2023-01-24 05:26 UTC, duboisp commented on templates/organizational/includes/org-info.html
> +<section class="gc-crprt">
Would this code sample be in the "components" under "gc-crprt"

2023-01-24 05:26 UTC, duboisp commented on templates/localnav/index-en.html
> +		<section class="lnkbx">
Comment: `lnkbx` CSS seem to be an utility component by itself

2023-01-25 13:19 UTC, Garneauma commented
> * [x]  Code sample should be in the "samples" folder instead of "includes"
> * [x]  Move `gc-crprt` as a components outside templates

Done ! :)

2023-02-02 13:26 UTC, duboisp approved these changes

2023-02-06 15:17 UTC, merged