WCAG upgrage - add an test & example file for alerts
wet-boew/GCWeb pull request #2114
Opened 2023-03-03 16:34 UTC by shiva-sc

2023-03-06 13:33 UTC, duboisp requested changes

2023-03-15 01:55 UTC, duboisp requested changes
I reviewed and after the small content change, we will be able to merge this change request.

* [ ] Remove the word "optional" for alert description

2023-03-15 01:55 UTC, duboisp commented on common/alert/alerts-en.html
> +	<p>Optional alert details.</p>
This change to be applied to the other alert variant.

```suggestion
	<p>Alert details.</p>
```

Semantically we can not have a section that consist into being a single heading. An heading is always followed with content or inner sections.

2023-03-15 19:22 UTC, duboisp requested changes

2023-03-15 19:22 UTC, duboisp commented on common/alert/alerts-en.html
> +
Remove this code sample as it don't match the immediate preceding working example "Alerts without Headings"

2023-03-15 19:22 UTC, duboisp commented on common/alert/alerts-fr.html
> +
To ensure we are conforming to "Language in page"
```suggestion
<p>Cette page nécessite une traduction.</p>
<div lang="en">
```

2023-03-15 19:22 UTC, duboisp commented on common/alert/alerts-fr.html
> +</code></pre>
```suggestion
</code></pre>
</div>
```

2023-03-17 18:52 UTC, duboisp requested changes
There is a few change. Don't forget to apply the same similar change at the French version too.

2023-03-17 18:52 UTC, duboisp commented on common/alert/alerts-en.html
> +</strong>&lt;section <strong>class=&quot;alert alert-warning&quot;</strong>&gt;
Remove the empty `strong`. This is a SC 1.3.1 issue.

```suggestion
//Warning Alert with a heading
&lt;section <strong>class=&quot;alert alert-warning&quot;</strong>&gt;
```

2023-03-17 18:52 UTC, duboisp commented on common/alert/alerts-fr.html
> +	</strong>&lt;section <strong>class=&quot;alert alert-info&quot;</strong>&gt;
```suggestion
	//Info Alert with a heading
	&lt;section <strong>class=&quot;alert alert-info&quot;</strong>&gt;
```

2023-03-17 18:52 UTC, duboisp commented on common/alert/index.json-ld
> +	"componentName": "tables",
This component name is "alert". 
```suggestion
	"componentName": "alert",
```

Note: Having the wrong component name create a broken link in our main index page when it get generated by jekyll.

2023-03-17 18:52 UTC, duboisp commented on common/alert/alerts-en.html
> +&lt;p&gt; Success content goes here &lt;a href=&quot;#&quot; <strong>class=&quot;alert-link&quot;</strong>&gt;link text&lt;/a&gt;.&lt;/p&gt;
The heading is missing here:

```suggestion
<pre><code>&lt;section <strong>class=&quot;alert alert-success&quot;</strong>&gt;
&lt;h3>(Success Title)&lt;/h3>
&lt;p&gt; Success content goes here &lt;a href=&quot;#&quot; <strong>class=&quot;alert-link&quot;</strong>&gt;link text&lt;/a&gt;.&lt;/p&gt;
```

2023-03-17 18:52 UTC, duboisp commented on common/alert/alerts-en.html
> +&lt;p&gt; Info content goes here &lt;a href=&quot;#&quot; <strong>class=&quot;alert-link&quot;</strong>&gt;link text&lt;/a&gt;.&lt;/p&gt;
```suggestion
&lt;h3>(Info Title)&lt;/h3>
&lt;p&gt; Info content goes here &lt;a href=&quot;#&quot; <strong>class=&quot;alert-link&quot;</strong>&gt;link text&lt;/a&gt;.&lt;/p&gt;
```

2023-03-17 18:52 UTC, duboisp commented on common/alert/alerts-en.html
> +&lt;p&gt; Warning content goes here &lt;a href=&quot;#&quot; <strong>class=&quot;alert-link&quot;</strong>&gt;link text&lt;/a&gt;.&lt;/p&gt;
```suggestion
&lt;h3>(Warning Title)&lt;/h3>
&lt;p&gt; Warning content goes here &lt;a href=&quot;#&quot; <strong>class=&quot;alert-link&quot;</strong>&gt;link text&lt;/a&gt;.&lt;/p&gt;
```

2023-03-17 18:52 UTC, duboisp commented on common/alert/alerts-en.html
> +&lt;p&gt; Danger content goes here &lt;a href=&quot;#&quot; <strong>class=&quot;alert-link&quot;</strong>&gt;link text&lt;/a&gt;.&lt;/p&gt;
```suggestion
&lt;h3>(Danger Title)&lt;/h3>
&lt;p&gt; Danger content goes here &lt;a href=&quot;#&quot; <strong>class=&quot;alert-link&quot;</strong>&gt;link text&lt;/a&gt;.&lt;/p&gt;
```

2023-03-17 18:52 UTC, duboisp commented on common/alert/alerts-en.html
> +</strong>&lt;section <strong>class=&quot;alert alert-warning&quot;</strong>&gt;
This code sample don't represent the HTML that is preceding as we should expect.
```suggestion
<h3>Code</h3>
<pre><code>&lt;h3> Success alert &lt;/h3>
&lt;div class="alert alert-success">
	&lt;p>(Success content here.)&lt;/p>
&lt;/div>

&lt;h3> Info alert &lt;/h3>
&lt;div class="alert alert-info">
	&lt;p> Info content here. &lt;/p>
&lt;/div>

&lt;h3> Warning alert &lt;/h3>
&lt;div class="alert alert-warning">
	&lt;p>(Warning content here.)&lt;/p>
&lt;/div>

&lt;h3> Danger alert &lt;/h3>
&lt;div class="alert alert-danger">
	&lt;p>(Danger content here.)&lt;/p>
&lt;/div>
```

2023-03-17 20:34 UTC, shiva-sc commented
@duboisp Can you please let me know, if these are final changes to be made;

2023-03-18 03:44 UTC, duboisp commented
@shiva-sc that is most likely the final changes to ensure the working example is conform to our web standard and illustrating the use of those style. There is always a risk, which are lowered at every review, to have additional change request. I don't see those as new requirement because published content must meet all our web standard at the time of publishing.

2023-03-22 00:51 UTC, duboisp approved these changes
Reviewed and tested locally,

It's coded and work as expected.

2023-03-22 00:52 UTC, duboisp commented on common/alert/alerts-en.html
> +</strong>&lt;section <strong>class=&quot;alert alert-warning&quot;</strong>&gt;
The requested change was applied

2023-03-22 00:52 UTC, duboisp commented on common/alert/alerts-en.html
> +&lt;p&gt; Danger content goes here &lt;a href=&quot;#&quot; <strong>class=&quot;alert-link&quot;</strong>&gt;link text&lt;/a&gt;.&lt;/p&gt;
The requested change was applied

2023-03-22 00:52 UTC, duboisp commented on common/alert/alerts-en.html
> +&lt;p&gt; Warning content goes here &lt;a href=&quot;#&quot; <strong>class=&quot;alert-link&quot;</strong>&gt;link text&lt;/a&gt;.&lt;/p&gt;
The requested change was applied

2023-03-22 00:52 UTC, duboisp commented on common/alert/alerts-en.html
> +&lt;p&gt; Info content goes here &lt;a href=&quot;#&quot; <strong>class=&quot;alert-link&quot;</strong>&gt;link text&lt;/a&gt;.&lt;/p&gt;
The requested change was applied

2023-03-22 00:52 UTC, duboisp commented on common/alert/alerts-en.html
> +&lt;p&gt; Success content goes here &lt;a href=&quot;#&quot; <strong>class=&quot;alert-link&quot;</strong>&gt;link text&lt;/a&gt;.&lt;/p&gt;
The requested change was applied

2023-03-22 02:35 UTC, duboisp commented on common/alert/alerts-fr.html
> +	</strong>&lt;section <strong>class=&quot;alert alert-info&quot;</strong>&gt;
The requested change was applied

2023-03-22 02:35 UTC, duboisp commented on common/alert/alerts-en.html
> +</strong>&lt;section <strong>class=&quot;alert alert-warning&quot;</strong>&gt;
The requested change was applied

2023-03-22 02:36 UTC, duboisp commented on common/alert/alerts-en.html
> +
The requested change was applied

2023-03-22 02:36 UTC, merged