Update Search pages
wet-boew/GCWeb pull request #2136
Opened 2023-03-23 14:08 UTC by ouafaaetta

Update Search page with a new Search disclaimer message in WET-335

2023-03-27 14:53 UTC, GormFrank requested changes
Svp utiliser l'apostrophe uniformément : `'` au lieu de `’`

2023-03-27 14:53 UTC, GormFrank commented on templates/search/results-advanced-en.html
> +		<p id="gc-pi" class="mrgn-tp-md">Don’t include personal information (telephone, email, SIN, financial, medical, or work details).</p>
```suggestion
		<p id="gc-pi" class="mrgn-tp-md">Don't include personal information (telephone, email, SIN, financial, medical, or work details).</p>
```

2023-03-27 14:53 UTC, GormFrank commented on templates/search/results-contextual-en.html
> +		<p id="gc-pi" class="mrgn-tp-md">Don’t include personal information (telephone, email, SIN, financial, medical, or work details).</p>
```suggestion
		<p id="gc-pi" class="mrgn-tp-md">Don't include personal information (telephone, email, SIN, financial, medical, or work details).</p>
```

2023-03-31 14:38 UTC, ouafaaetta reviewed
l'apostrophe ' au lieu de ’ est utilisé dans tous les fichiers uniformément

2023-04-19 12:50 UTC, GormFrank requested changes

2023-04-25 18:01 UTC, GormFrank requested changes
@ouafaaetta Tel que discuté; même corrections nécessaires en français.

Puis corriger les erreurs identifiés par le script "Continuous integration".

Merci :)

2023-05-01 15:23 UTC, GormFrank requested changes
@ouafaaetta Dernier petit changement, et aussi régler les problèmes identifiés par le **Build** (continuous integration) svp.

2023-05-08 14:11 UTC, duboisp reviewed
pre-approved upon successful testing and review

2023-05-08 18:06 UTC, GormFrank approved these changes

2023-05-09 03:18 UTC, duboisp approved these changes
Tested and reviewed and this PR is ready to be merged. 

This is a major change for the template but it is a "moderated used" template according to our versioning API. We will need to specify in the release note that a communication about that would be sent in June 2023 so we will be able to mark it as a minor change for the GCWeb product.

@ouafaaetta There is only the following two content update which you can quickly do later this week:
* [x] add in the `pages.examples` grouping "results-advanced-en.html" and "result-advanced-fr.html" in the index.json-ld file
* [ ] add in the `pages.docs` grouping  "api-fr.html" in the index.json-ld

2023-05-09 03:22 UTC, merged