Crochefort authentification
wet-boew/GCWeb pull request #2139
Opened 2023-03-28 20:01 UTC by crochefort

PR pour cette issue : fix #2138  

La différence es au niveau que c'Est pas des <button> mais <a href avec la classe btn-default.

Il vas falloir corrigé la couleur pour possiblement les autres sortes de bouton

2023-03-28 21:32 UTC, duboisp commented
@Garneauma can you generate and post a link to a working example for this PR? Thank you.

2023-03-30 12:46 UTC, Garneauma commented
Demo link: https://servicecanada.github.io/wet-boew-demos/gcweb-pr2139/index.html

2023-04-03 14:27 UTC, duboisp commented
DTO will take a quick look to ensure it is conform to their guidance.

Here a direct link to the newly added example: https://servicecanada.github.io/wet-boew-demos/gcweb-pr2139/sites/authentication/activeusersession-en.html

Which seems to be/will be used through a CDTS and leverage some icon for the session management.

cc @delisma @catalinaperezn 

---

Todo:

* [ ] (For wet-boew team) Add documentation to the authentication pattern to mention we do support an additional variant.

cc @GormFrank

2023-04-03 18:35 UTC, catalinaperezn commented
We'll review it this week with the whole group at DTO.

2023-04-04 19:00 UTC, GormFrank requested changes

2023-04-12 12:12 UTC, catalinaperezn commented
Good morning friends. Sorry if I'm not doing this correctly. We are learning how to work together on different platforms. At DTO we reviewed the request and we have some questions we put in a google doc we are sending ... It's a draft but I wanted to share it fast instead of waiting for it to be perfect! We can iterate later... @duboisp @GormFrank  @delisma https://docs.google.com/document/d/1C0Ma7aasJ6iKl253nIbGuyO2J1ZOV4wl1az9_Vl15p8/edit?usp=sharing

2023-04-17 14:35 UTC, duboisp commented
Will work on a way to present this demo pattern as a community variant and to find a way to illustrate that there is no official guidance approved that support this variant.

2023-05-01 14:35 UTC, duboisp commented
Tomorrow at the office hours, PP and DTO would discuss on how we can merge this PR without creating false perception of "Official pattern" vs "Community pattern" vs "Trusted pattern" when presenting those working example.

2023-06-14 05:06 UTC, duboisp commented
@Garneauma lorsque tu auras la chance, est ce que tu pourrais mettre à jour le démo temporaire? merci.

2023-06-14 15:55 UTC, GormFrank requested changes
Just a few spelling mistakes

2023-06-14 15:55 UTC, GormFrank commented on _includes/alert-community-stable.html
> +	<p>Veuillez noter que la présente page web représente une contribution communautaire et qu'elle <strong>ne bénéficie pas</strong> de la validation ni de l'approbation formelle du bureau de la transf
```suggestion
	<p>Veuillez noter que la présente page web représente une contribution communautaire et qu'elle <strong>ne bénéficie pas</strong> de la validation ni de l'approbation formelle du Bureau de la transformation numérique comparativement à une conception officielle. Il est à souligner que cette contribution ne va pas à l'encontre d'une version officielle publiée au moment de l'ajout. Si une conception officielle équivalente est élaborée et soit formellement publiée, il est possible que la conception démontrée sur la présente page en diffère en partie ou en totalité.</p>
```

2023-06-14 15:55 UTC, GormFrank commented on _includes/alert-community-stable.html
> +	<p>This <strong>stable</strong> design do share the same benefits as any other stable functionality and designs as defined by the <a href="https://wet-boew.github.io/wet-boew-documentation/decision/
```suggestion
	<p>This <strong>stable</strong> design do share the same benefits as any other stable functionalities and designs as defined by the <a href="https://wet-boew.github.io/wet-boew-documentation/decision/14.html">GCWeb public versioning API draft</a>.</p>
```

2023-07-04 14:24 UTC, duboisp commented
Pre-approved once the change is completed and a second review completed.

2023-07-06 12:36 UTC, duboisp commented on _includes/alert-community-stable.html
> +	<p>Veuillez noter que la présente page web représente une contribution communautaire et qu'elle <strong>ne bénéficie pas</strong> de la validation ni de l'approbation formelle du bureau de la transf
fixed

2023-07-06 12:36 UTC, duboisp commented on _includes/alert-community-stable.html
> +	<p>Cette conception est <strong>stable</strong> et par conséquent elle bénificie des mêmes avantages que toutes autres fonctioanlité et conceptions stable tel que définie par <a href="https://wet-bo
fixed

2023-07-06 12:36 UTC, duboisp commented on _includes/alert-community-stable.html
> +	<p>This <strong>stable</strong> design do share the same benefits as any other stable functionality and designs as defined by the <a href="https://wet-boew.github.io/wet-boew-documentation/decision/
fixed

2023-07-06 12:38 UTC, duboisp commented on sites/authentication/includes/authentication.html
> +		<p><a class="btn btn-sm btn-default" href="#"><span class="glyphicon glyphicon-user"></span> {{ i18nText-signUsername }}</a>
We will apply a more global fix when we will officially assess and fix the glyphicon component to make it fully conform to WCAG 2.1

2023-07-06 12:39 UTC, duboisp commented on sites/authentication/includes/authentication.html
> +		<a class="btn btn-sm btn-primary" href="#"><span class="glyphicon glyphicon-off"></span> {{ i18nText-signOut }}</a></p>
We will apply a more global fix when we will officially assess and fix the glyphicon component to make it fully conform to WCAG 2.1

2023-07-06 19:09 UTC, GormFrank approved these changes
Solid first iteration of the Community stable alert box.

2023-07-06 20:05 UTC, merged