Méli-mélo: Remove SASS line comment from CSS file
wet-boew/GCWeb pull request #2143
Opened 2023-04-04 22:05 UTC by EricDunsworth

Fixes an "invalid property name" error in the ``cssmin`` task.

2023-04-11 14:26 UTC, duboisp requested changes

2023-04-11 14:26 UTC, duboisp commented on méli-mélo/2021-04-gcaem/css/mandatetracker.css
> -	// width: 5em;
You can replace it by a CSS comment considering it is ignored anyway. Let's keep it for historical purpose
```
/* width: 5em; */
```

2023-04-11 15:28 UTC, EricDunsworth commented on méli-mélo/2021-04-gcaem/css/mandatetracker.css
> -	// width: 5em;
Done, updated commit incoming :).

2023-04-11 16:19 UTC, EricDunsworth commented
Turns out that the SASS line comment existed in both the "source" and "frozen" méli-mélo CSS files. Plus the build system uses the "frozen" CSS file (so my initial commit didn't actually fix anything).

My latest force-push has copied the fix into the "frozen" CSS file too. But that technically goes against the [rules in the compilation gelé page](https://wet-boew.github.io/GCWeb/m%C3%A9li-m%C3%A9lo/compilation-gel%C3%A9/index.html) since it isn't a major accessibility/security fix.

@duboisp What's your take on this?

2023-04-17 14:49 UTC, duboisp requested changes
Can we send to the build or configure dynamically to exclude the frozen compilation or only take the active one.

For example, we do have the active compilation here: https://github.com/wet-boew/GCWeb/blob/master/_data/m%C3%A9li-m%C3%A9lo.json#L3

And the méli-mélo compilation are limited at this folder: https://github.com/wet-boew/themes-dist/tree/26d0148935b1cc211f7f36d1551066782c02d38b/GCWeb/m%C3%A9li-m%C3%A9lo

Or feel free to exclude this folder: https://github.com/wet-boew/themes-dist/tree/26d0148935b1cc211f7f36d1551066782c02d38b/GCWeb/m%C3%A9li-m%C3%A9lo but we need to keep a min version of those files

2023-04-17 14:49 UTC, duboisp commented on méli-mélo/compilation-gelé/2021-04-gcaem.css
> +	/* width: 5em; */
Please undo this change.

2023-04-17 22:05 UTC, EricDunsworth commented
Just force-pushed an update to remove the "frozen" file edit and revise the commit message.

Btw I haven't tried digging very deeply into the main review comment yet. I'll need to wrap my head around it and investigate later.

2025-03-12 15:24 UTC, EricDunsworth commented
Closing since #2494 superseded both this and #2492.

2025-03-12 15:24 UTC, closed without merging