WCAG upgrade - Create test page for: Color (foreground/background)
wet-boew/GCWeb pull request #2149
Opened 2023-04-18 14:50 UTC by BrahimMahadi

This pull request includes a test page with working examples filled with lorem ipsum text for Utilities/helpers. More info can be found by referencing WET-319.

2023-04-20 15:12 UTC, duboisp requested changes
Here a quick review

* [ ] The site footer ACR would need to be removed from this PR. The easiest way to make this change will be to use a local git client to make the changes.
* [ ] Missing the French content equivalent page
* [ ] Missing the index.json-ld which will contains the metadata for this common component
* [ ] I quickly saw that the heading structure for the "colour.html" page need to be adjusted like at line 62 where it should be an h5 instead of being an h4

2023-04-20 15:12 UTC, duboisp commented on sites/footers/reports/a11y-1-en.hbs
The propose change for this file need to be put in another PR (if that not already the case)

2023-04-20 15:12 UTC, duboisp commented on sites/footers/reports/a11y-1-fr.hbs
The propose change for this file need to be put in another PR (if that not already the case)

2023-04-20 15:12 UTC, duboisp commented on sites/footers/reports/a11y-1.json
The propose change for this file need to be put in another PR (if that not already the case)

2023-04-28 16:17 UTC, BrahimMahadi commented on sites/footers/index.json-ld
Removed footer files from this PR.

2023-04-28 16:17 UTC, BrahimMahadi commented on sites/footers/reports/a11y-1-en.hbs
Removed footer files from this PR.

2023-04-28 16:17 UTC, BrahimMahadi commented on sites/footers/reports/a11y-1.json
Removed footer files from this PR.

2023-04-28 16:18 UTC, BrahimMahadi commented on sites/footers/reports/a11y-1-fr.hbs
Removed footer files from this PR.

2023-06-09 18:52 UTC, closed without merging