Update institution-landing-en.html
wet-boew/GCWeb pull request #2161
Opened 2023-05-11 18:05 UTC by jmealing

- Remove provisional classes
- Add Minister's photos
- Contact us on it's own in the band
- Change doormat column count to have same behaviour as homepage
- Margin class adjustment to fix Social Media component issues (hopefully)

To do:
[ ] Need a space to preview to validate it looks and behaves correctly
[ ] FR version
[ ] Add CSS for the bold class
[ } DTO to create documentation

2023-05-15 14:48 UTC, duboisp commented
For your review @duboisp later this week

2024-04-12 02:39 UTC, duboisp requested changes
@Garneauma do you think we can have a little bit of JS that can detect this is an ILP page  based on the number/type of component on the page? That way we could be able to implement a fall-back to add the CSS class `page-type-ilp` on the page body element.

We will need to mention it in the instruction, for MWS where the author must choose the content type "navigation page - institutional profile" via the basic page property but I don't think they would necessary think of it proactively. With this method, we can also throw a warning about that in the browser console.

Note that we will need to update the page context feature in the MWS to implement the bodyClass `page-type-ilp` when the content type "navigation page - institutional profile" is choosen.

What do you think? Open to suggestion/solution.

cc @GormFrank @jonasg-gc

2024-04-15 14:15 UTC, Garneauma commented
Pre-approved upon successful review, conflict resolution, added logic to detect the template.

2024-04-15 20:18 UTC, duboisp requested changes
There is a few editorial changes, but other than that it looks very good and we will be able to merge after.

2024-04-15 20:18 UTC, duboisp commented on templates/institutional-landing/institutional-landing-fr.html
> +	</section>
Note: to add a new sample in gc-srvinfo for this 3 column configuration

https://github.com/wet-boew/GCWeb/tree/master/components/gc-servinfo/samples

2024-04-15 20:18 UTC, duboisp commented on templates/institutional-landing/institutional-landing-fr.html
> +dateModified: "2024-03-22"
Put today date

```suggestion
dateModified: "2024-04-15"
```

2024-04-15 20:18 UTC, duboisp commented on templates/institutional-landing/institutional-landing-en.html
> +dateModified: "2024-03-22"
Put today date

```suggestion
dateModified: "2024-04-15"
```

2024-04-15 20:18 UTC, duboisp commented on templates/institutional-landing/index.json-ld
> +	"modified": "2024-03-26",
Put today dates

```suggestion
	"modified": "2024-04-15",
```

2024-04-15 20:18 UTC, duboisp commented on templates/institutional-landing/institutional-landing-fr.html
> +			</section>
Use the code sample to be included instead

```suggestion
		{%- include components/gc-features/features.html -%}
```

2024-04-15 20:18 UTC, duboisp commented on templates/institutional-landing/index.json-ld
> +				],
Add the following similar instruction:
* The author need to add the `page-type-ilp` CSS class on their page `<body>` element. Note: If you don't, the heading level 2 are not going to be at the right size according to the guidance. We did implemented a temporary workaround to give the time to Web CMS to implement it. The workaround are going to be removed at the same time of the demote/deprecated ILP version 1

Also, a little addition for the last instruction item:
```suggestion
				"en": [
					"Refer to the working example for a code sample.",
					"Refer to the working example and the guidance for more information on how to implement this page template."
				],
```

2024-04-15 20:18 UTC, duboisp commented on templates/institutional-landing/index.json-ld
> +					"Référez-vous aux directives officielles pour plus d'informations sur l'implémentation ce modèle de page."
```suggestion
					"Référez-vous à l'exemple pratique et aux directives pour plus d'informations sur l'implémentation ce modèle de page."
```

2024-04-16 11:47 UTC, Garneauma commented on templates/institutional-landing/_screen-sm-max.scss
> +	.gc-followus {
Je viens de réaliser que ce changement est propre au gabarit ILP. Il ne sera pas appliqué au gc-follow-us.

2024-04-16 13:43 UTC, Garneauma commented on templates/institutional-landing/institutional-landing-en.html
> +		<div class="col-md-8">{%- include /design-patterns/gc-institution/gc-institution.html -%}</div>
The normalization will need to be done at a later date as changing the include to a sample will require changes to more than 20 files.

2024-04-16 15:08 UTC, duboisp commented on templates/institutional-landing/_screen-sm-max.scss
> +	.gc-followus {
Parfait, merci de confirmer

2024-04-16 15:20 UTC, duboisp requested changes
2 little change,
* Remove the alternate page link for the test example
* Add a comment about the limited life span for the JS code

Optional, can done at a later date: The documentation are not showing link to the accessibility assessment we did. Probably the documentation template need to be adjusted.

2024-04-16 15:20 UTC, duboisp commented on templates/institutional-landing/institutional-landing-bad.html
> +altLangPage: "institutional-landing-fr.html"
Considering there is no translation for this page and it is only used for testing. Just don't provide an `altLangPage` which will auto remove the language toggle link.

```suggestion
```

2024-04-16 15:20 UTC, duboisp commented on templates/institutional-landing/institutional-landing.js
> + * @overview Logic to detect pages that seem to be institutional landing pages without the appropriate class
Can you mention this is temporary measure until that proper fix is implemented by content management system. This code are going to be deprecated and removed at the same time of the version 1 of the ILP template. It just need to be aligned with our technical implementation note.

2024-04-16 18:57 UTC, duboisp approved these changes
Review and tested locally,

Everything work as expected.

2024-04-16 18:58 UTC, merged