removal provisional class
wet-boew/GCWeb pull request #2163
Opened 2023-05-15 17:58 UTC by jmealing

- removed provisional class

2023-12-01 20:50 UTC, Garneauma commented
@jmealing After discussing with the team, we came to a conclusion where we are questioning the utility of the `.gc-feeds` component since the only thing it changes is that the feed links are bolded (all other styles don't do anything).

If the intention for the feed component is to **always** have bolded links, we could simply overwrite WET-BOEW's styles for the GCWeb theme instead of creating a new component. According to design decision 14 (https://wet-boew.github.io/wet-boew-documentation/decision/14.html), this would only be a patch since the visual difference is arguably barely noticeable for the average Canada.ca user.

If the intention for the feed component is to **never** have bolded links, we could simply get rid of the component altogether.

We can discuss this during next week's office hours if you prefer.

2023-12-06 18:25 UTC, jmealing commented
@Garneauma @delisma The intention is to make the news items links always bold, to carry the same visual weight as the other links throughout the templates that use this pattern.

If there's a different way to go about it, then by all means. I've looped in David E in case there's a technical challenge or reason I'm not understanding

2024-01-11 20:18 UTC, jmealing commented
@Garneauma This one isn't working for me to be able to do anything anymore. There is no folder for /wet-boew and when I try and rebase to get it there's all kinds of conflicts for stuff I didn't touch @duboisp @delisma

2024-01-11 20:19 UTC, jmealing commented
<img width="411" alt="Screenshot 2024-01-11 at 3 19 07 PM" src="https://github.com/wet-boew/GCWeb/assets/31008799/b0fc9e25-acbe-46a9-a0f3-a4f10cb2ba89">
<img width="437" alt="Screenshot 2024-01-11 at 3 19 14 PM" src="https://github.com/wet-boew/GCWeb/assets/31008799/75a436c9-f9e7-4307-9441-5e01bffe2fd0">
<img width="540" alt="Screenshot 2024-01-11 at 3 19 24 PM" src="https://github.com/wet-boew/GCWeb/assets/31008799/1acc4820-a050-4b8c-84af-eb2526329d57">

2024-01-17 12:56 UTC, Garneauma commented
@jmealing Did this PR only have the change listed in the "Files changed" tab? (components/gc-feeds/_base.scss)

@duboisp Would you know how to fix this? Should @jmealing simply `git reset --hard upstream/master` and reapply changes?

2024-01-17 14:03 UTC, jmealing commented
I updated 3 files:
```
gc-feeds-fr.html
gc-feeds-en.html
/gc-feeds/_base.scss
```

The conflicts which won't let me merge are all within the `package-lock.json` file

2024-01-29 14:25 UTC, Garneauma requested changes
This PR is very close to being merged. Please apply changes to the JSON-LD, then I think it'll be good!

Thank you @jmealing !

2024-01-29 14:25 UTC, Garneauma commented on wet-boew/feeds/index.json-ld
> +				"path": "https://wet-boew.github.io/gcweb-compiled-demos/wetboew-demos/feeds/feeds-en.html"
```suggestion
				"title": "Feeds",
				"language": "en",
				"url": "https://wet-boew.github.io/gcweb-compiled-demos/wetboew-demos/feeds/feeds-en.html"
```

2024-01-29 14:25 UTC, Garneauma commented on wet-boew/feeds/index.json-ld
> +				"path": "https://wet-boew.github.io/gcweb-compiled-demos/wetboew-demos/feeds/feeds-fr.html"
```suggestion
				"title": "Fils de syndication",
				"language": "fr",
				"url": "https://wet-boew.github.io/gcweb-compiled-demos/wetboew-demos/feeds/feeds-fr.html"
```

2024-01-29 14:25 UTC, Garneauma commented on wet-boew/feeds/index.json-ld
> +				"title": "Feeds GC overrides - Documentation.",
```suggestion
				"title": "Feeds",
```

2024-01-29 14:25 UTC, Garneauma commented on wet-boew/feeds/index.json-ld
> +				"path": "https://wet-boew.github.io/wet-boew/docs/ref/feeds/feeds-en.html"
```suggestion
				"url": "https://wet-boew.github.io/wet-boew/docs/ref/feeds/feeds-en.html"
```

2024-01-29 14:25 UTC, Garneauma commented on wet-boew/feeds/index.json-ld
> +				"title": "Fils de syndication remplacement GC - Documentation",
```suggestion
				"title": "Fils de syndication",
```

2024-01-29 19:27 UTC, jmealing commented
@Garneauma This one can be merged when it is ready. We don't have guidance that directly links to or from this component

2024-01-30 13:54 UTC, Garneauma requested changes
@jmealing Can you accept those change requests? Sorry I hadn't noticed the description yesterday. Once it is done, I will approve this PR.

Thank you for your contribution!

2024-01-30 13:54 UTC, Garneauma commented on wet-boew/feeds/index.json-ld
> +		"en": "Overrides the WET ATOM feeds to apply GC design pattern.",
```suggestion
		"en": "Aggregates and displays entries from one or more Web feeds.
--


",
```

2024-01-30 13:54 UTC, Garneauma commented on wet-boew/feeds/index.json-ld
> +		"fr": "Remplace les Fils de syndication pour appliquer le modèle de conception GC."
```suggestion
		"fr": "Affiche les articles d’un ou plus fils de syndication."
```

2024-01-30 15:28 UTC, Garneauma approved these changes

2024-02-12 15:06 UTC, duboisp commented
Pre-approved upon final/quick review by @duboisp

2024-02-13 13:26 UTC, duboisp approved these changes
Like the `h1.thickline` we need to note that the provisional feature `gc-feed` which as been conjointly used with the `wb-feed` plugin is now obsolete because it is the new default. That is not a blocker to merge this PR.

2024-02-13 13:37 UTC, merged