WCAG upgrade -- add an example for table of contents
wet-boew/GCWeb pull request #2173
Opened 2023-06-16 13:24 UTC by shiva-sc

2023-07-13 04:33 UTC, duboisp requested changes
A few little change but after we should be good to merge this PR.

Great work on this.

2023-07-13 04:33 UTC, duboisp commented on components/gc-toc/toc-en.html
> +<h2 id="toc">In-page table of contents</h2>
Don't need this heading because it duplicate the content of the heading level 1. And bump the sub-heading one level up

2023-07-13 04:33 UTC, duboisp commented on components/gc-toc/toc-en.html
> +	<h3>On this page</h3>
```suggestion
	<h2>On this page</h2>
```

2023-07-13 04:33 UTC, duboisp commented on components/gc-toc/toc-en.html
> +	"title": "GCWeb Table of Contents example",
Don't need to specify "GCWeb" here

```suggestion
	"title": "In-page table of contents",
```

2023-07-13 04:33 UTC, duboisp commented on components/gc-toc/toc-fr.html
> +	"title": "GCWeb Table des matières example",
```suggestion
	"title": "Table des matières à l'intérieur de la page",
```

2023-07-13 04:33 UTC, duboisp commented on components/gc-toc/toc-fr.html
> +<h2 id="toc">Table des matières à l’intérieur de la page</h2>
```suggestion
```

2023-07-13 04:33 UTC, duboisp commented on components/gc-toc/toc-fr.html
> +	<h3>Sur cette page</h3>
```suggestion
	<h2>Sur cette page</h2>
```

2023-08-17 19:02 UTC, duboisp requested changes

2023-08-17 19:02 UTC, duboisp commented on components/gc-toc/toc-en.html
> +	</ul>
The last heading should be there considering it is an h2 sibling

```suggestion
		<li><a href="#section3">Third section heading</a></li>
		<li><a href="#code">Code</a></li>
	</ul>
```

2023-08-17 19:02 UTC, duboisp commented on components/gc-toc/toc-en.html
> +<h2>Code</h2>
```suggestion
<h2 id="code">Code</h2>
```

2023-08-17 19:43 UTC, shiva-sc commented on components/gc-toc/toc-en.html
> +<p>The In-Page Table of Contents Pattern is a list of links that lead to subsections of the same page. This pattern is intended for long documents that exist as a single page.</p>
@duboisp : Can you please suggest changes that needs to be done for FR page?

2023-08-17 20:26 UTC, duboisp requested changes

2023-08-17 20:26 UTC, duboisp commented on components/gc-toc/toc-fr.html
> +<p>La configuration relative à la table des matières à l’intérieur de la page consiste en une liste de liens dirigeant vers des sous-sections de la même page. Cette configuration est utilisée pour le
```suggestion
<p>Consultez les conseils pour la<a href="https://conception.canada.ca/configurations-conception-communes/table-matiere-interieur.html">table des matières à l’intérieur de la page</a>.</p>
```

2023-08-17 20:48 UTC, shiva-sc commented
@duboisp Thanks, I have pushed my changes

2023-08-18 18:58 UTC, duboisp approved these changes

2023-08-18 18:59 UTC, merged