Release v13.3.1
wet-boew/GCWeb pull request #2180
Opened 2023-06-29 14:52 UTC by ouafaaetta

2023-06-29 20:35 UTC, duboisp requested changes
Need to apply fixes to:
* [ ] index-en.md
* [x] _data/common.json

---

Dans _data/common.json il faut rajouter ceci comme dernier élément de la liste.

```
,{
	"@context": {
		"@version": 1.1,
		"dct": "http://purl.org/dc/terms/",
		"title": { "@id": "dct:title", "@container": "@language" },
		"description": { "@id": "dct:description", "@container": "@language" },
		"modified": "dct:modified"
	},
	"title": {
		"en": "Tables",
		"fr": "Les Tables"
	},
	"description": {
		"en": "Tables with custom styles",
		"fr": "Tableaux avec des styles personalisés."
	},
	"modified": "2023-02-28",
	"componentName": "tables",
	"processing": "baseline",
	"status": "stable",
	"pages": {
		"examples": [
			{
				"title": "Tables",
				"language": "en",
				"path": "table-en.html"
			},
			{
				"title": "Tables",
				"language": "fr",
				"path": "table-fr.html"
			}
		]
	}
}
]
```

2023-06-29 20:35 UTC, duboisp commented on index-en.md
À la ligne 457, il faut changer "commun" pour "common".

Voici la modification à apporter avec la ligne qui précède et qui suit.

```
									{% if example.path %}
									<li><a href="common/
												{%- if item.componentName -%}
```

2023-06-30 13:43 UTC, ouafaaetta commented on index-en.md
done

2023-06-30 16:07 UTC, duboisp approved these changes
I reviewed and it's now ready to be merged

2023-06-30 16:08 UTC, merged