Step by step navigation: adding documentation
wet-boew/GCWeb pull request #2181
Opened 2023-06-30 14:29 UTC by Garneauma

Adding .gc-stp-stp documentation and example.

2023-08-18 18:12 UTC, duboisp requested changes
Would you like to create a include for this component and to update the "advanced service" template to use that include?

And I can see there is new CSS added for this component, is that necessary or probably a minor/patch change to the component?

2023-08-18 18:12 UTC, duboisp commented on components/gc-stp-stp/gc-stp-stp-en.html
> +</div>
This don't like the version 2 of the component.

This is not a "toc" (table of content) if we compare on how the "toc" CSS is currently used for the in-page table of content component.

2023-09-11 14:11 UTC, duboisp commented
Pre-approved upon review and local testing.

To be confirm: The CSS code for the download link might need to be removed as it was already moved I think.

2023-09-12 12:35 UTC, Garneauma commented
Removed the .gc-dwnld CSS. It was added by mistake during merge conflict resolution.

2023-09-12 14:08 UTC, duboisp approved these changes
Review and tested locally,

Work as expected. 

This is a minor change because it add another supported pattern for the gc step step which is the same as the version 1 but simpler to code for an author.

2023-09-12 14:10 UTC, merged