pre-assesment gc-freatures
wet-boew/GCWeb pull request #2187
Opened 2023-07-06 13:06 UTC by ipaksc

2023-08-25 03:22 UTC, duboisp requested changes
I reviewed and tested locally.

Other than the little change, everything look good once that change is completed.

2023-08-25 03:22 UTC, duboisp commented on components/gc-features/reports/a11y-1-fr.html
> +	"reportURL": "a11y-1.json"
The name need to be adjusted.

```suggestion
	"reportURL": "pre-a11y-1.json"
```

2023-08-25 13:02 UTC, ipaksc commented on components/gc-features/reports/a11y-1-fr.html
> +	"reportURL": "a11y-1.json"
Fixed

2023-08-31 00:16 UTC, duboisp approved these changes
Reviewed and tested locally. Work as expected.

Thanks @ipaksc for the pre-assessment and the assessment

2023-08-31 00:16 UTC, merged