Content - Borders - Created example pages
wet-boew/GCWeb pull request #2192
Opened 2023-07-11 14:18 UTC by SebastianBurke

related to: WET-396

2023-07-14 18:17 UTC, GormFrank requested changes
Thank you for your contribution @SebastianBurke 🥇 

**IMPORTANT:** All of my requested changes apply to French page as well.

2023-07-14 18:17 UTC, GormFrank commented on common/borders/borders-en.html
> +	<dd>Set a border below the element</dd>
You are missing the following classes: `.brdr-0` (to remove borders) and `.brdr-rds-0` (to remove border radius)

2023-07-14 18:17 UTC, GormFrank commented on common/borders/borders-en.html
> +	</div>
Please remove the Correct uses and the Compliance point, this is out-of-scope for GCWeb :)

2023-07-14 18:17 UTC, GormFrank commented on common/borders/borders-en.html
> +</p>
Please remove this descriptive blurb, and instead bring to the top the list you created at the bottom of this page.

2023-07-14 18:17 UTC, GormFrank commented on common/borders/borders-en.html
> +				</p>
You are missing two examples, one for `.brdr-0` and one for `.brdr-rds-0`

2023-07-14 18:17 UTC, GormFrank commented on common/borders/borders-en.html
> +                    &lt;p <strong>class=&quot;brdr-bttm&quot;</strong>&gt;...&lt;/p&gt;</code></pre>
Don't forget to add the code samples for the 2 missing examples.

2023-08-17 17:10 UTC, duboisp requested changes
There is an issue with your commit, you will need to remove the "merge" flag. The simplest will be to recreate the commit and then update your branch.

FYI  here the commit details
![image](https://github.com/wet-boew/GCWeb/assets/1676030/6be8ee0d-56cc-42a4-8934-4e1837e53780)

2023-08-17 17:10 UTC, duboisp commented on common/borders/borders-en.html
> +<h3>CSS Class</h3>
This create an issue with the page structure when jekyl generate the HTML final page. The heading level 2 is missing. 
Heading should always be in sequence.

Considering this page is short, I suggest to simply use a paragraph here.

```suggestion
<p>CSS Class</p>
```

2023-08-17 17:10 UTC, duboisp commented on common/borders/borders-en.html
> +				<h3 class="mrgn-tp-0">Appearance</h3>
Considering the page start with an h1 (heading level 1) created by jekyl by using the "title" property in your front-matter. This heading would need to be changed for an heading level 2.

```suggestion
				<h2>Appearance</h2>
```

(No need to remove the top margin here. FYI - If it was used in panel, then the panel title must be moved into the panel heading section.)

2023-08-17 17:10 UTC, duboisp commented on common/borders/borders-en.html
> +					Example 6
Be more descriptive with the text. Include the expected style. 

```suggestion
					Example of a left border
				</p>
				<p class="brdr-tp">
					Example of a top border
				</p>
				<p class="brdr-rght">
					Example 3
				</p>
				<p class="brdr-bttm">
					Example 4
				</p>
				<p class="brdr-0">
					Example 5
				</p>
				<p class="brdr-rds-0">
					Example 6
```

2023-08-17 17:10 UTC, duboisp commented on common/borders/borders-fr.html
> +		<div class="panel panel-default">
I think the intend was to have it side by side so this is missing

```suggestion
		</div>
	</div>
	<div class="col-md-6">
		<div class="panel panel-default">
```

Note: I am assuming that you are also removing the panel for the code sample, I kept it here to show how to configure the Grid

2023-08-31 01:03 UTC, duboisp requested changes

2024-03-06 20:18 UTC, closed without merging