wet-370 Conduct WCAG pre-assessment for Toggle (GCWeb)
wet-boew/GCWeb pull request #2202
Opened 2023-07-17 13:45 UTC by hongbinyu413

2023-09-07 21:03 UTC, duboisp requested changes
In addition to the request change, Can you add an index.json-ld file in the folder "common/toggle" like how I did for the share this page like this: https://github.com/wet-boew/GCWeb/blob/master/common/share/index.json-ld

Thanks

2023-09-07 21:03 UTC, duboisp commented on common/toggle/reports/ally-1-en.html
> +	"reportURL": "pre-a11y-1.json"
```suggestion
	"altLangPage": "ally-1-fr.html",
	"dateModified": "2023-07-06",
	"layout": "assessment_wrote_en-en",
	"reportURL": "pre-ally-1.json"
```

2023-09-07 21:03 UTC, duboisp commented on common/toggle/reports/pre-ally-1.json
> +            "@value": "gc-features"
This CSS selector are not accurate.

```suggestion
            "@value": ".wb-toggle"
```

2023-09-07 21:03 UTC, duboisp commented on common/toggle/reports/ally-1-fr.html
> +	"reportURL": "a11y-1.json"
```suggestion
	"altLangPage": "ally-1-en.html",
	"dateModified": "2023-07-06",
	"layout": "assessment_wrote_en-fr",
	"reportURL": "ally-1.json"
```

2024-02-28 22:18 UTC, hanseller commented
I made the changes and push it to  HeansiH: PR2202

2024-02-28 22:39 UTC, duboisp commented
https://github.com/HeansiH/GCWeb/commits/PR2202/

2024-02-28 22:45 UTC, duboisp commented
I pushed @hanseller changes into this PR

2024-02-28 22:45 UTC, duboisp approved these changes
Reviewed and tested locally. All good.

2024-02-28 22:46 UTC, duboisp commented on common/toggle/reports/ally-1-en.html
> +	"reportURL": "pre-a11y-1.json"
fixed, idem in French

2024-02-29 16:20 UTC, merged