Wet 369
wet-boew/GCWeb pull request #2203
Opened 2023-07-17 13:45 UTC by hongbinyu413

2023-09-07 21:14 UTC, duboisp requested changes
* [ ] The html files to contain the similar issue as the other PR for the toggles. 
* [ ] Rename the folder "tab inteface" for the plugin technical name
* [ ] Create the index.json-ld file, similar to what I did for the share this page plugin.

2023-09-07 21:14 UTC, duboisp commented on common/tabs interface/reports/pre-ally-1.json
> +            "@value": "gc-features"
The CSS selector need to be replaced by the tab-interface CSS selector

2024-02-13 21:33 UTC, AtlakM approved these changes
looks good

2024-02-13 21:37 UTC, AtlakM requested changes
css selector needs update

2024-02-13 21:41 UTC, duboisp requested changes
All those 3 files need to be moved into this folder: `/wet-boew/wb-tabs/reports`

2024-02-13 21:41 UTC, duboisp commented on common/tabs interface/reports/pre-ally-1.json
> +            "@value": "tab-interface"
```suggestion
            "@value": ".wb-tabs"
```

2024-02-13 21:41 UTC, duboisp commented on common/tabs interface/reports/pre-ally-1.json
Rename file for "ally-1.json"

2024-02-13 21:41 UTC, duboisp commented on common/tabs interface/reports/ally-1-fr.html
> +	"reportURL": "a11y-1.json"
```suggestion
	"title": "Assessment d'accessibilité #1 - Interface à onglets",
	"language": "fr",
	"description": "Partielle. Évaluation des nouveaux critères de succès aux niveaux A et AA de WCAG 2.1 et WCAG 2.2",
	"altLangPage": "ally-1-en.html",
	"dateModified": "2023-07-06",
	"layout": "assessment_wrote_en-fr",
	"reportURL": "ally-1.json"
```

2024-02-13 21:41 UTC, duboisp commented on common/tabs interface/reports/ally-1-en.html
> +	"reportURL": "pre-a11y-1.json"
```suggestion
	"title": "Accessibility assessment #1 - Tabbed Interface",
	"language": "en",
	"description": "Partial. Evaluation of new Success Criteria at Level A and Level AA of WCAG 2.1 and WCAG 2.2",
	"altLangPage": "ally-1-fr.html",
	"dateModified": "2023-07-06",
	"layout": "assessment_wrote_en-en",
	"reportURL": "ally-1.json"
```

2025-10-01 17:33 UTC, Garneauma commented
Superseded by #2314

2025-10-01 17:33 UTC, closed without merging