WET-400: Creating Working example for Generic content page En & Fr
wet-boew/GCWeb pull request #2213
Opened 2023-07-20 16:33 UTC by ouafaaetta

Creating Working example for Generic content page En & Fr

2023-08-25 17:58 UTC, ouafaaetta commented
move the generic existing content pages working example to their own folder created separately

2023-08-31 00:55 UTC, duboisp requested changes
https://github.com/wet-boew/GCWeb/blob/master/templates/index.json-ld#L21-L64
Il faudrait enlever les examples dans le fichier index du templates qui ont été déplacer dans le template "content-page"

2023-08-31 00:55 UTC, duboisp commented on templates/content-page/content.json-ld
Ce fichier dois être spécifiquement nommé "index.json-ld"

2023-08-31 00:55 UTC, duboisp commented on templates/content-page/content.json-ld
> +	"modified": "2023-08-24",
Il manque le nom du template via la propriété `componentName`

```suggestion
	"modified": "2023-08-24",
	"componentName": "content-page",
```

2023-08-31 15:03 UTC, duboisp approved these changes
Reviewed and tested locally.

Work as expected and this is only a content change

2023-08-31 15:04 UTC, merged