gc-featured-link: adding bg color option
wet-boew/GCWeb pull request #2214
Opened 2023-07-20 18:35 UTC by Garneauma

Adding option to customize the background colour of featured links.

Added CSS to hide the customized link by default to prevent a colour flick on load.

2023-07-25 15:00 UTC, GormFrank requested changes
Partial review

2023-08-07 16:34 UTC, Garneauma commented on components/gc-featured-link/gc-featured-link.js
> +			elm.style.display = "block";
Great suggestion. Done.

2023-08-22 15:39 UTC, duboisp requested changes
* [ ] This is broken in basic HTML mode, we should still display the featured banner. In basic mode I can see a white text with a white background.
* [ ] How do we ensure the text inside the banner do have and maintain a sufficient contrast ratio? Should we auto switch the text color between black and white depending of the luminosity of the background color that was set?

2023-08-23 02:42 UTC, duboisp requested changes
I love the way it is setup and do self-adjust to ensure it meet the contrast ratio.

2023-08-23 02:42 UTC, duboisp commented on components/gc-featured-link/_base.scss
> +			background-color: transparent;
We would need to set a default text color which we do know its going to be rewritten when the plugin are initialized.

2023-08-23 02:42 UTC, duboisp commented on components/gc-featured-link/gc-featured-link-en.html
> +	<p class="mrgn-tp-lg">Dark background example:</p>
We would need to add a notice about the irregular heading structure along with a skip link to the code sample.

2023-08-23 02:42 UTC, duboisp commented on components/gc-featured-link/gc-featured-link-en.html
> +	<h3>Code</h3>
Should this be an heading 4 considering this is a subsection of "Customized background color"

2023-08-24 14:53 UTC, duboisp requested changes
Testé localement et ça fonctionne tel que prévu, il va rester à adjuster la couleur du texte par défaut juste avant que l'initialization soit complété.

2023-08-24 14:53 UTC, duboisp commented on components/gc-featured-link/_base.scss
> +.gc-featured-link.provisional {
ceci nous avais causé quelque problème d'override. on va devoir utiliser une nouvelle stratégie pour identifier les provisional feature et les retirer/neutralisé le cas échéant.

Enlève la classe `.provisional`

2023-08-24 14:53 UTC, duboisp commented on components/gc-featured-link/_base.scss
> +		color: #fff;
Considérant que notre background est white-smoke je crois que la couleur de text adéquat serait noir et non blanc.

```suggestion
		color: #000;
```

Et un override additionnelle sera requis pour les ancres

```suggestion
		color: #000;
		
		a {
			color: #000;
		}
```

2023-08-28 14:28 UTC, duboisp reviewed
Pre-approved upon the default loading style in standard mode do have sufficient contrast ratio

2023-08-29 17:23 UTC, duboisp approved these changes
Tested locally and reviewed. Every work as expected.

2023-08-29 17:24 UTC, merged