Update and-or.css
wet-boew/GCWeb pull request #2219
Opened 2023-08-02 21:51 UTC by Christopher-O

Updated CSS to allow brdr-0 to exist on all resolutions when the design is stacked, and not just "always stacked".

2023-08-07 14:37 UTC, duboisp commented
Pre-approved upon review and after confirming there is an example of this change.

2023-08-07 14:40 UTC, duboisp commented
pre-approved upon testing

Relates to 
* #2219 
* #2220 
* #2221

2023-08-08 13:38 UTC, Christopher-O commented
@duboisp there is an example of the update on index.html under the updated header of no border.

2023-08-15 03:33 UTC, duboisp approved these changes
Tested the CSS change which are demoed in PR 2220 and work as expected. All CSS is demoed as expected.

Todo:
* [ ] Merge all other PRs into a single one.

2023-08-15 03:44 UTC, duboisp requested changes
Fix the HTML markup in the edge-cases.html. The [`<s>` element](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-s-element) can only be use in phrasing context according to HTML 5 spec.

Other than that, the rest is good to be squash and merge

2023-08-15 03:44 UTC, duboisp commented on méli-mélo/2021-05-conjunction/edge-cases.html
> +<s><h2>No border shall not work for responsive break point</h2>
The `<s>` element should be use in the phrasing context not as a flow content.

I suggest to instead put this content inside a details/summary with a title that inform the content are not long accurate. Or simply you can remove those outdated instruction.

What would you like to do?
* [ ] Replicate the `<s>` element for every phrasing context in the deprecated instruction block
* [ ] Move the content inside a details summary with a title saying it is deprecated instruction
* [ ] Remove the outdated instruction.

2023-08-15 19:11 UTC, duboisp commented on méli-mélo/2021-05-conjunction/edge-cases.html
> +<s><h2>No border shall not work for responsive break point</h2>
I replicated the `<s>` on every sub element to ensure it is used as phrasing content.

2023-08-15 19:38 UTC, duboisp approved these changes
Tested and reviewed locally

2023-08-15 20:04 UTC, merged