WET-379 Main container working example
wet-boew/GCWeb pull request #2222
Opened 2023-08-03 15:11 UTC by josephdiab

2023-08-15 15:56 UTC, duboisp requested changes

2023-08-15 15:56 UTC, duboisp commented on common/main-container/maincontainer-article-en.html
> +{%- endcapture -%}
```suggestion
{%- include variable-core.liquid -%}
{%- capture page-title -%}
	{%- if page.titleH1 -%}
		{{ page.titleH1 }}
	{%- elsif page.title -%}
		{{ page.title }}
	{%- else -%}
		Page untitled
	{%- endif -%}
{%- endcapture -%}
```

2024-03-12 04:49 UTC, duboisp requested changes

2024-03-12 04:49 UTC, duboisp commented on common/main-container/maincontainer-article-en.html
> +		<h3>Article</h3>
This need to be an h1

2024-03-12 04:49 UTC, duboisp commented on common/main-container/maincontainer-article-en.html
> +    </code></pre>
Move the code inside the article and replace the h3 by an h2

2024-03-12 04:49 UTC, duboisp commented on common/main-container/maincontainer-en.html
> +	<h3>Lorem Ipsum</h3>
```suggestion
	<h1 id="wb-cont">Lorem Ipsum</h1>
```

2024-03-12 04:49 UTC, duboisp commented on common/main-container/maincontainer-en.html
> +	<h3>Code</h3>
```suggestion
	<h2>Code</h2>
```

2024-03-12 04:49 UTC, duboisp commented on common/main-container/maincontainer-fr.html
> +	<h3>Lorem Ipsum</h3>
```suggestion
	<h1 id="wb-cont">Lorem Ipsum</h1>
```

2024-03-12 04:49 UTC, duboisp commented on common/main-container/maincontainer-fr.html
> +	<h3>Code</h3>
```suggestion
	<h2>Code</h2>
```

2024-03-12 04:49 UTC, duboisp commented on common/main-container/maincontainer-article-fr.html
> +    </code></pre>
Move the code inside the article and replace the h3 by an h2

2024-03-12 04:49 UTC, duboisp commented on common/main-container/maincontainer-article-fr.html
> +		<h3>Article</h3>
```suggestion
		<h1 id="wb-cont">Article</h1>
```

2024-03-12 04:49 UTC, duboisp commented on common/main-container/maincontainer-section-en.html
> +		<h3>Section</h3>
```suggestion
		<h1 id="wb-cont">Section</h1>
```

2024-03-12 04:49 UTC, duboisp commented on common/main-container/maincontainer-section-en.html
> +    </code></pre>
Move inside the section, the h3 need to be an h2

2024-03-12 04:49 UTC, duboisp commented on common/main-container/maincontainer-section-fr.html
> +		<h3>Section</h3>
```suggestion
		<h1 id="wb-cont">Section</h1>
```

2024-03-12 04:49 UTC, duboisp commented on common/main-container/maincontainer-section-fr.html
> +    </code></pre>
Move inside the section and the h3 need to be h2

2024-03-12 04:49 UTC, duboisp commented on common/main-container/reports/pre-a11y-1.json
> +      "@value": "title, meta, #wb-bc, main"
Here we are only testing the main element, so the selector should be `main`

```suggestion
      "@value": "main"
```

2024-03-12 04:49 UTC, duboisp commented on package-lock.json
This file need to be removed from the commit.

2024-03-12 04:52 UTC, duboisp commented
@AtlakM can you apply the requested changes. Thanks and comment in which of your GitHub branch we can find the changes

2024-03-12 05:01 UTC, duboisp requested changes
Tested and reviewed, see the requested changes.

2024-03-12 05:03 UTC, duboisp requested changes

2024-03-12 05:03 UTC, duboisp commented on common/main-container/index.json-ld
> +		]
Add the report section like:

Please replace the title and the link to match the reports pre-assessement file on this PR.

```suggestion
		],
		"reports": [
			{
				"title": "Accessibility assessment #1",
				"language": "en",
				"path": "reports/a11y-2-en.html"
			},
			{
				"title": "Évaluation de l'accessibilité #1",
				"language": "fr",
				"path": "reports/a11y-2-fr.html"
			}
		]
```

2024-03-27 18:40 UTC, AtlakM commented
> @AtlakM can you apply the requested changes. Thanks and comment in which of your GitHub branch we can find the changes

https://github.com/AtlakM/GCWeb/commits/main-container/

2024-03-27 21:34 UTC, duboisp requested changes
A few last change requested. I think this are going to the last change.

2024-03-27 21:34 UTC, duboisp commented on common/main-container/maincontainer-article-fr.html
> +		&lt;/main&gt;
This code sample don't match this page example
```suggestion
		&lt;main property="mainContentPage"&gt;
			&lt;article&gt;
			&lt;!-- heading --&gt;
		&lt;h1&gt;Article&lt;/h1&gt;

			&lt;!-- contenu de la page --&gt;

			&lt;!-- Section des détails de la page [Doit être configuré comme un élément &lt;footer&gt; dans cette situation] --&gt;

			&lt;/article&gt;
		&lt;/main&gt;
```

2024-03-27 21:34 UTC, duboisp commented on common/main-container/maincontainer-fr.html
> +	</code></pre>
Code sample don't match

2024-03-28 20:03 UTC, AtlakM commented
> A few last change requested. I think this are going to the last change.

https://github.com/AtlakM/GCWeb/commit/4be26cc4e65da2504d4ad9e0802ef65d3654558d

2024-03-28 21:27 UTC, duboisp approved these changes
Review and fixed the merge conflict.

This is a content change.

2024-03-28 21:58 UTC, duboisp approved these changes
The JSON parsing error is not fixed. This can be merged on the CI build is completed

2024-03-29 12:33 UTC, merged