bold class EN
wet-boew/GCWeb pull request #2237
Opened 2023-08-25 15:23 UTC by jmealing

Update the well-bold class component to be independent of a well to be more flexible in applying bold to any element, such as the Contact us band, or the About the institution component used in the ILP.

To do:
[ ] FR version

2023-10-18 14:08 UTC, Garneauma commented
@jmealing I suggest adding the utility class `.fnt-bld` in WET-BOEW instead of renaming this component. We would then deprecate the `.well-bold` plugin.

You can simply add the class in "src/base/proximity/_base.scss", right under `.fnt-nrml`.

2023-10-18 17:55 UTC, jmealing commented
@Garneauma I don't have that file anywhere `"src/base/proximity/_base.scss"` to be able to edit it

The only place in my folders I've downloaded from the repo where I see that class is the `theme-srv.css` and `theme.css` files. How do I get to the one you want me to edit?

2023-10-18 18:53 UTC, Garneauma requested changes
Hi @jmealing, after discussing with @duboisp, we decided to keep the code in GCWeb. So, forget my last comment.

The new approach is to rename the class to `.bold-content` (but keep `.well.well-bold`) and rename the component to "Bold content".

We will deprecate `.well.well-bold`, but keep it for now.

Please add another working example above the `.well.well-bold` that does not contain a `.well` element. Keep the current example under it, but please add a message saying that it is now deprecated.

Also, make sure every file ends with a new empty line to pass build lint checker.

Thank you and let me know if you have any question!

2023-10-18 18:53 UTC, Garneauma commented on components/bold/_base.scss
> +.bold {
```suggestion
.bold-content, .well.well-bold {
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/bold-doc-en.html
> +description: "Documentation and working example for bold class"
```suggestion
description: "Documentation and working example for bolded content"
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/bold-doc-en.html
> +altLangPage: "bold-doc-fr.html"
```suggestion
altLangPage: "bold-content-doc-fr.html"
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/bold-doc-en.html
> +title: "bold"
```suggestion
title: "Bold content"
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/bold-doc-en.html
> +	<dd><code>bold</code></dd>
```suggestion
	<dd><code>bold-content</code></dd>
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/bold-doc-en.html
> +<p>This apply font weight bold to evey text element inside a component and generates normal font weight when the element <code>strong</code> is applied.</p>
```suggestion
<p>This apply font weight bold to every text element inside the component and generates normal font weight when the element <code>strong</code> is applied.</p>
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/bold-doc-en.html
> +	<li><a href="bold-en.html">Working example</a></li>
```suggestion
	<li><a href="bold-content-en.html">Working example</a></li>
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/bold-doc-en.html
> +<h3>Code</h3><pre><code>&lt;div class="well bold"&gt;
```suggestion
<h3>Code</h3><pre><code>&lt;div class="bold-content"&gt;
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/bold-doc-en.html
> +<p>Font weight bold is applied to evey text element inside a component and generates normal font weight when the element <code>strong</code> is applied.</p>
```suggestion
<p>Font weight bold is applied to every text element inside the component and generates normal font weight when the element <code>strong</code> is applied.</p>
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/bold-doc-fr.html
rename "bold-content-doc-fr.html"

2023-10-18 18:53 UTC, Garneauma commented on components/bold/bold-en.html
> +description: "Working example for the bold class"
```suggestion
description: "Working example for the bold content component."
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/bold-en.html
> +title: "Bold class"
```suggestion
title: "Bold content"
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/bold-en.html
> +	<li><a class="btn btn-primary" href="bold-doc-en.html">Documentation</a></li>
```suggestion
	<li><a class="btn btn-primary" href="bold-content-doc-en.html">Documentation</a></li>
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/bold-en.html
> +	<li><a class="btn btn-primary" href="https://github.com/wet-boew/GCWeb/issues/new?title=Bold">Questions or comments?</a></li>
```suggestion
	<li><a class="btn btn-primary" href="https://github.com/wet-boew/GCWeb/issues/new?title=Bold-content">Questions or comments?</a></li>
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/index.json-ld
> +		"fr": "En gras"
```suggestion
		"en": "Bold content",
		"fr": "Contenu en gras"
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/index.json-ld
> +		"fr": "X"
```suggestion
		"en": "This component applies font weight bold to every text element inside it and generates normal font weight when the element <code>strong</code> is applied.",
		"fr": "Ce composant applique une épaisseur de police en gras à chaque élément de texte qu'il contient et génère une épaisseur de police normale lorsque l'élément <code>strong</code> est appliqué."
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/index.json-ld
> +	"componentName": "bold",
```suggestion
	"componentName": "bold-content",
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/index.json-ld
> +				"path": "bold-fr.html"
```suggestion
				"title": "Bold content - working example",
				"language": "en",
				"path": "bold-content-en.html"
			},
			{
				"title": "Contenu en gras - example pratique",
				"language": "fr",
				"path": "bold-content-fr.html"
```

2023-10-18 18:53 UTC, Garneauma commented on components/bold/index.json-ld
> +			"path": "bold-doc-fr.html"
```suggestion
			"title": "Bold content",
			"language": "en",
			"path": "bold-content-doc-en.html"
		},
		{
			"title": "Contenu en gras",
			"language": "fr",
			"path": "bold-content-doc-fr.html"
```

2023-10-19 15:53 UTC, jmealing commented
Thanks @Garneauma. I accepted your changes and will review the files in full and get it to pass the lint checker

2023-12-04 13:48 UTC, Garneauma requested changes
This is a partial review:

- Rename all pages to use "bold-content" instead of "bold". For example: `bold-content-doc-en.html`.
- Rename folder to "bold-content".
- Update `theme.scss` to use the correct file URL (line 190).
- Update documentation page with a working example of the new class and a guideline on how to use it.

2023-12-18 18:09 UTC, Garneauma commented
@duboisp Something happened here. This PR went from 3 files changed to over 300. Would you know what caused that?

@jmealing

2023-12-20 16:56 UTC, jmealing commented
@Garneauma I rebased, maybe something went wrong? @delisma

2024-01-17 15:51 UTC, jmealing commented
@Garneauma @delisma @duboisp this one still has an issue when I rebased I ended up with a whole bunch of other files. Not sure why as I did the process to rebase that has been fine everywhere else.

2024-01-26 15:48 UTC, Garneauma commented
@delisma I believe this PR also needs to be fixed.

2024-01-26 15:50 UTC, jmealing commented
> @delisma I believe this PR also needs to be fixed.

We did go through it and fix it, what is still showing up as a problem for you?

2024-01-26 18:54 UTC, Garneauma commented
There seems to be some messed up file references in the files changed tab:
- components/bold/_base.scss~refs/remotes/upstream/master
- components/bold/index.json-ld~refs/remotes/upstream/master

Also, you will need to fix the remaining build issues.

2024-02-02 18:07 UTC, Garneauma submitted a review, later dismissed

2024-02-12 15:10 UTC, duboisp commented
Pre-approved upon review and local re-testing.

2024-02-13 19:52 UTC, duboisp submitted a review, later dismissed

2024-02-13 20:01 UTC, duboisp approved these changes
Reviewed,

We will need to change "deprecated" state by something saying this will be deprecated at the next major version.

2024-02-13 20:30 UTC, Garneauma approved these changes

2024-02-13 21:59 UTC, merged