Forms: WGAG 2.1 AA Assessment
wet-boew/GCWeb pull request #2252
Opened 2023-09-15 17:51 UTC by BrahimMahadi

### This pull request includes the WCAG 2.1 & 2.2 Accessibility assessment done for the forms page

General checklist
- [x] Updated forms documentation to include the accessibility assessment reports
- [x] Page was tested against WCAG for accessibility
- [x] Documentation is bilingual

2024-03-27 21:45 UTC, duboisp requested changes
I will wait for your report @AtlakM , we will add it to this PR. And can you fix the missing CSS selector

2024-03-27 21:45 UTC, duboisp commented on common/scaffolding/reports/a11y-2.json
> +      "@value": ""
Missing the CSS selector that identify what that has been tested for WCAG. Is it the whole page?

2024-03-28 20:39 UTC, AtlakM commented
> I will wait for your report @AtlakM , we will add it to this PR. And can you fix the missing CSS selector

https://github.com/AtlakM/GCWeb/commit/e77b916064763d4f26a4e58de13f45ea7bfad209

2024-03-28 21:10 UTC, duboisp requested changes
Just a few little change

2024-03-28 21:10 UTC, duboisp commented on common/scaffolding/reports/a11y-3.json
> +}
```suggestion
      "earl:outcome": "earl:passed"
    }
  ]
}
```

2024-03-28 21:12 UTC, duboisp approved these changes
Reviewed and it's look good. 

This is only a content change

2024-03-28 21:36 UTC, duboisp requested changes

2024-03-28 21:36 UTC, duboisp commented on common/scaffolding/reports/a11y-3.json
> +    }
The comma need to be removed.

```suggestion
      "earl:outcome": "earl:passed"
    }
```

2024-03-28 21:39 UTC, duboisp approved these changes
Looks good, the validation error was fixed.

2024-03-28 22:11 UTC, merged