WET-347
wet-boew/GCWeb pull request #2261
Opened 2023-09-26 21:08 UTC by ouafaaetta

2023-09-26 21:14 UTC, duboisp requested changes

2023-09-26 21:14 UTC, duboisp commented on components/header-rwd/index.json-ld
> +		"fr": "Liste - Style additionel"
Ceci ne correspond pas au composant "well header responsive"

2023-09-26 21:20 UTC, ouafaaetta commented on components/header-rwd/index.json-ld
> +		"fr": "Liste - Style additionel"
done

2023-09-26 21:26 UTC, duboisp commented
There is a merge conflict that need to be resolved

2023-09-28 18:10 UTC, duboisp submitted a review, later dismissed
Reviewed, the change looks good.

I will only update the _data/component.json generated file into this PR, so the change will be immediately effective.

2023-09-29 07:00 UTC, duboisp approved these changes

2023-09-29 15:31 UTC, merged