Content - Feedback - Update documentation
wet-boew/GCWeb pull request #2262
Opened 2023-09-26 22:27 UTC by duboisp

* Apply updates to implementation as discussed with DTO during office hours 
* Improved the code sample displayed in the working example
* Fix the grunt script to not rely on a generated file when initiating any task
* Updated the generated content

2023-09-27 12:33 UTC, duboisp commented
@LanaStewa FYI

2023-09-28 13:58 UTC, Garneauma requested changes
- [x] Quelques changements de contenu.
- [ ] Pourrais-tu également modifier l'URL du ajax-replace pour: "https://canada.ca/etc/designs/canada/wet-boew/assets/feedback/page-feedback-en.html".

2023-09-28 13:58 UTC, Garneauma commented on sites/feedback/index.json-ld
> +					"Pour des conseils supplémentaires sur la mise en œuvre, vous pouvez consulter le guide sur GCPedia avec les autres documents du service web géré."
```suggestion
					"Pour des conseils supplémentaires sur la mise en œuvre de l'Outil de rétroaction sur la page, vous pouvez consulter le guide sur GCPedia avec les autres documents du SWG."
```

2023-09-28 13:58 UTC, Garneauma commented on sites/feedback/index.json-ld
> +				"en": "This implementation is meant for developers/publishers adding the component manually with using the latest GCWeb version along with at least the implementation of the page details version
```suggestion
				"en": "This implementation is meant for developers/publishers adding the component manually while using the latest version of GCWeb along with the implementation of the page details version 2.0 and above.",
```

2023-09-28 13:58 UTC, Garneauma commented on sites/feedback/index.json-ld
> +				"fr": "Cette implémentation est destinée aux développeurs/éditeurs qui ajoutent le composant manuellement en utilisant une version récente de GCWeb avec l'implémentation de la version 2.x du déta
```suggestion
				"fr": "Cette implémentation est destinée aux développeurs/éditeurs qui ajoutent le composant manuellement en utilisant la dernière version de GCWeb avec l'implémentation de la version 2.0 ou plus du détails de la page."
```

2023-09-28 13:58 UTC, Garneauma commented on sites/feedback/index.json-ld
> +					"Vérifier que la <a href=\"../page-details/page-details-docs-en.html\">version 2.1, ou plus récente, du détails de la page</a> est implémenté",
```suggestion
					"Vérifier que la <a href=\"../page-details/page-details-docs-en.html\">version 2.1, ou plus récente, du détails de la page</a> est implémentée.",
```

2023-09-29 17:19 UTC, Garneauma approved these changes

2023-09-29 17:20 UTC, merged