Application: adding application template and examples
wet-boew/GCWeb pull request #2267
Opened 2023-10-16 18:28 UTC by Garneauma

Adding CDTS application elements inside an "Application" template.

2023-10-30 14:22 UTC, duboisp commented
Pre-approved upon successful review and testing

2023-11-01 14:27 UTC, duboisp requested changes
@Garneauma Il faudrait faire une petite documentation rapide afin d'officialiser la version 1 de ce template.

---

@GormFrank @delisma @bsouster Qu'est-ce que vous pensez de l'utilisation du double h1 pour indiquer le nom de l'application? Ou, est-ce que vous avez une solution alternative qui respecterait le modèle visuelle de cette page tout en étant conforme au WCAG 2.1. Vous pouvez voir le markup proposé via le fichier modifier de ce PR "templates/application/layouts/application.html"

Il faut considérer que ce PR a pour but principal d'éliminer l'utilisation de CSS custom dans CDTS concernant leur application template actuelle et qu'éventuellement nous allons devoir prendre le temps nécessaire afin de revoir entièrement l'application template. L'objectif ici c'est d'avoir rapidement un modèle conforme à l'accessibilité et qui maintient l'expérience visuelle qui a été implémenté dans CDTS et utilisé par les applications web utilisant CDTS.

Voici les examples pratiques
* https://universallabs.org/wet/labs/pr2267/templates/application/default-application-en.html
* https://universallabs.org/wet/labs/pr2267/templates/application/application-with-banner-en.html

Moi, @duboisp, je crois que l'utilisation du double h1 ici pourrait être satisfaisant pour ce gabarit jusqu'à ce qu'on prenne le temps de revoir ce gabarit dans son entièreté.

2023-11-02 12:41 UTC, Garneauma commented
> @GormFrank @delisma @bsouster Qu'est-ce que vous pensez de l'utilisation du double h1 pour indiquer le nom de l'application? Ou, est-ce que vous avez une solution alternative qui respecterait le modèle visuelle de cette page tout en étant conforme au WCAG 2.1. Vous pouvez voir le markup proposé via le fichier modifier de ce PR "templates/application/layouts/application.html"

@GormFrank @delisma @bsouster Après discussion avec @duboisp, l'idée d'utiliser le double H1 a été mise de côté. Le nom de l'application utilise maintenant un H2.

2023-11-02 20:11 UTC, duboisp requested changes

2023-11-02 20:11 UTC, duboisp commented on templates/application/_base.scss
> +	h2 {
Should the font size be fixed at 28px and 18px depending of the view port and 34px for print media?

* https://github.com/wet-boew/cdts-sgdc/blob/master/public/gcweb/cdtsapps.css#L309
* https://github.com/wet-boew/cdts-sgdc/blob/master/public/gcweb/cdtsapps.css#L123
* https://github.com/wet-boew/cdts-sgdc/blob/master/public/gcweb/cdtsapps.css#L363

2023-11-02 20:11 UTC, duboisp commented on templates/application/application-docs-en.html
I was thinking to leverage our new data-first documentation template. But let's chat first about it.

2023-11-17 16:52 UTC, GormFrank commented
> > @GormFrank @delisma @bsouster Qu'est-ce que vous pensez de l'utilisation du double h1 pour indiquer le nom de l'application? Ou, est-ce que vous avez une solution alternative qui respecterait le modèle visuelle de cette page tout en étant conforme au WCAG 2.1. Vous pouvez voir le markup proposé via le fichier modifier de ce PR "templates/application/layouts/application.html"
> 
> @GormFrank @delisma @bsouster Après discussion avec @duboisp, l'idée d'utiliser le double H1 a été mise de côté. Le nom de l'application utilise maintenant un H2.

@Garneauma @duboisp @delisma @bsouster I agree with the H2 approach. I personnally believe that it doesn't cause any semantics problems, as well as UX.

2023-11-28 16:16 UTC, duboisp requested changes
A few item for discussion.

2023-11-28 16:16 UTC, duboisp commented on templates/application/layouts/application.html
> +					{%- if page.infoBanner.link.external -%}
I am not sure about that property name. Having an external link don't means we should enforce the exit-script plugin.

What do you think if we just don't add support for opening the page in a popup + no support for exit script. But we keep the icon if the link was marked to be external.

2023-11-28 16:16 UTC, duboisp commented on sites/theme.scss
> +	@import "../templates/application/screen-xs-max";
This import are not inserted in the right location. For example it is expected to work in `.xxsmallview`.

I suggest to move it near line 233

2023-12-11 15:41 UTC, duboisp commented
Pre-approved upon another review and local testing.

2023-12-12 07:12 UTC, duboisp approved these changes
Reviewed and tested locally,

Everything work as expected. With this change we are going to be able to initiate the removal of custom CSS used by CDTS

2023-12-12 07:22 UTC, merged