Content - Spacing - Created Example Pages
wet-boew/GCWeb pull request #2275
Opened 2023-11-07 13:53 UTC by SebastianBurke

Accidentally deleted old PR while trying to amend.
Changes reflected here

2024-02-14 20:41 UTC, duboisp requested changes
You will need to re-create the commit because it is tagged as a merge commit.

The easiest is to redo the change and then do a force push to your branch "spacing".

Let's connect to do that.

2024-02-14 22:36 UTC, duboisp requested changes
As discussed, please add an example of each style documented in the card.

Thanks

2024-03-12 03:59 UTC, duboisp requested changes
I tested locally and the content look good.

Please apply the content re-ordering proposition.

Optionally, it will be great if you can update the heading with a human readable text which describe the associated demo.

2024-03-12 03:59 UTC, duboisp commented on common/spacing-borders/spacing-borders-en.html
> +</div>
Can you move those example at the bottom of the page as they are not recommended. They were only added to ease a transition between WET 3 to WET 4.

Please put it in a section named "Spacing utility not recommended" followed by an expand/collapse to view those item where you will downgrade the h2 for an h3. Something like:

```
<h2>Spacing utilities that are not recommended</h2>
<details>
<summary>Only to ease fast content transition from WET 3 to WET 4</summary>

<h3><code>.margin-bottom-none</code></h3>
....

</details>
```

2024-03-12 03:59 UTC, duboisp commented on common/spacing-borders/spacing-borders-en.html
> +</div>
Move those items to be the first item in this example page.

2024-03-12 03:59 UTC, duboisp commented on common/spacing-borders/spacing-borders-en.html
> +	<h2><code>.mrgn-*-*</code></h2>
This change is optional for the purpose of this working example but if you do it you will need to update all the other heading to be consistant. And do the same in French.

Ideally we will have a more meaningful name like:

```suggestion
	<h2>Margin generic utilities - <code>.mrgn-*-*</code></h2>
```

2025-10-01 17:21 UTC, Garneauma approved these changes

2025-10-01 17:25 UTC, merged