Feedback: deprecating RAP and Page details 2.0
wet-boew/GCWeb pull request #2277
Opened 2023-11-08 15:29 UTC by Garneauma

- Deprecating RAP
- Deprecating Page details 1.1 and 2.0
- Updating code samples with correct characters

2023-11-15 19:50 UTC, duboisp requested changes
2 little change request. 

Other than that its all good. I reviewed all the code and tested locally.

2023-11-15 19:50 UTC, duboisp commented on sites/page-details/index.json-ld
Deprecate the version 2.x and make the version 2.1 to be the version 3.0 of the component.

Remove the implementation of version 2 and create its own change set by duplicating the one you created.

2023-11-15 19:50 UTC, duboisp commented on sites/feedback/index.json-ld
Through the implementation, this "version 2.1" need to be change for "version 3.0" in regard of the page details.

2023-11-15 22:15 UTC, duboisp requested changes
One little change because we released page-details version 3.

2023-11-16 13:12 UTC, Garneauma commented
> One little change because we released page-details version 3.

Done. Sorry, I missed that.

2023-11-16 13:55 UTC, merged