Assessment about input focus and add assets support for a11y report
wet-boew/GCWeb pull request #2288
Opened 2023-11-22 15:06 UTC by duboisp

This is a content change

* Assessment about input focus 
* Add support to display assets in our web accessibility assessment report
* Add the i18n text for displaying the report section on the main GCWeb page

cc @shawnthompson

2023-11-22 18:59 UTC, Garneauma requested changes
Simples petits changements textuels.

2023-11-22 18:59 UTC, Garneauma commented on _data/i18n.yml
> +    reports: Raports
```suggestion
    reports: Rapports
```

2023-11-22 18:59 UTC, Garneauma commented on common/scaffolding/reports/a11y-1.json
> +            "dct:description": "Color contrast is not enough when an input field receive the focus. The contrast measured is: 2.2:1",
```suggestion
            "dct:description": "Color contrast is not enough when an input field receives the focus. The contrast measured is: 2.2:1",
```

2023-11-22 18:59 UTC, Garneauma commented on common/scaffolding/reports/a11y-1.json
> +                "dct:title": "Visual capture of the input element when it receive focus\nContains the following text: Title saying 'The (code) input (end code) element'; Sub heading saying 'Implicit
```suggestion
                "dct:title": "Visual capture of the input element when it receives focus\nContains the following text: Title saying 'The (code) input (end code) element'; Sub heading saying 'Implicit labeling'; Label saying 'Label:'; an input field with a blue focus border; Code sample of the preceding which says '<form><label>Label: <input></label>'",
```

2023-11-23 13:25 UTC, Garneauma approved these changes

2023-11-23 13:26 UTC, merged

2023-11-23 13:56 UTC, duboisp commented
@shawnthompson here the permanent link of your assessment: https://wet-boew.github.io/GCWeb/common/scaffolding/reports/a11y-1-en.html