Field flow: Detect anchors via firstElementChild
wet-boew/GCWeb pull request #2328
Opened 2024-03-06 18:01 UTC by EricDunsworth

Anchors were previously detected by evaluating ``firstChild``'s node name... which only worked if the very first node was an anchor element.

As a result, if the first node was something other than an element (e.g. comment or text node with empty space)... they'd be evaluated instead of the real anchor and consequently mess up the redirection action.

This resolves it by evaluating ``firstElementChild`` instead of ``firstChild``. Also adds an empty space to one of the redirection examples.

2024-03-11 15:43 UTC, EricDunsworth commented
Just force-pushed a couple of super minor updates:
* Mention the comment example in the commit message (previously only mentioned empty space)
* Update modified dates

2024-03-27 14:34 UTC, Garneauma requested changes
@EricDunsworth There is a javascript error: `theme.js:2550 Uncaught TypeError: Cannot read properties of null (reading 'nodeName')`

2024-03-27 14:47 UTC, EricDunsworth commented
@Garneauma Ugh sorry :(. Will fix it in a sec.

When I prepped/tested this PR on my end, I edited my "built" theme.js file directly and everything worked fine... except I forgot to copy a snippet of code into the src folder's fieldflow script 🙃.

My next force-push will change this:
```js
if ( firstElmNode.nodeName === "A" ) { ... }
```

Into this:
```js
if ( firstElmNode && firstElmNode.nodeName === "A" ) { ... }
```

2024-03-27 14:54 UTC, EricDunsworth commented
Just force-pushed the the aforementioned change and updated modified dates.

@Garneauma Thanks for catching that 👍!

2024-04-03 14:06 UTC, EricDunsworth commented
Just rebased, updated modified dates and force-pushed the outcome :).

2024-04-03 14:31 UTC, Garneauma submitted a review, later dismissed
Works very well. Thank you for this fix @EricDunsworth.

2024-04-08 14:24 UTC, EricDunsworth commented
Just rebased, updated modified dates and force-pushed :).

The merge conflicts turned out to be just the dates.

2024-04-08 17:52 UTC, Garneauma approved these changes

2024-04-08 17:53 UTC, merged