Institutional landing page: adding AEM instructions
wet-boew/GCWeb pull request #2352
Opened 2024-04-26 15:06 UTC by Garneauma

Adding instructions for AEM users on how to implement the page template.

2024-04-30 03:04 UTC, duboisp requested changes
See the inline suggestion. 

I reviewed and other than the suggestion, everything looks good from a technical perspective. I confirm this is a content change.

As discussed today, we will wait for PP to review the wording prior to merge this PR.

2024-05-13 14:40 UTC, duboisp commented
I will follow up internally about the wording to unblock this PR.

2024-05-16 19:15 UTC, duboisp requested changes

2024-05-16 19:15 UTC, duboisp commented on templates/institutional-landing/index.json-ld
> +				],
```suggestion
					"Create a page with the <strong>Generic template</strong>",
					"Applying Content type (navigation page – institutional profile) via the page <strong>Properties</strong> -> <strong>Basic tab</strong> -> <strong>Content type</strong>, set the value to “<strong>navigation page – institutional profile</strong>”.",
					"Configure Page container manually via the page <strong>Properties</strong> -> <strong>Template options</strong> tab -> <strong>Advanced</strong>, check “<strong>Page container: Configure manually</strong>”.",
					"Configure your ILP page. The ILP page contains several GCWeb components. Each component has its own configuration which you can adapt as per your institutional needs. Please see individual component for more details about their configurable options."
					"Remove the <strong>H1 Title</strong>.",
					"Add the ILP HTML code with a <strong>Generic HTML component</strong> component.",
					"Edit the ILP HTML code"
				],
```

2024-05-16 22:05 UTC, duboisp requested changes
The instruction looks good and looks to be aligned with the formal AEM instruction.

See the additional change in the inline comments.

The item regarding the data-ajax are out of scope from this PR but we should submit a fix for the next wet-boew release.

In this PR, can you remove the link toward the working copy of the institution landing page which was linked from its old location. I am referring to the following line of code:
https://github.com/wet-boew/GCWeb/blob/master/templates/institutional/index.json-ld#L52-L61

2024-05-17 15:00 UTC, Garneauma commented on templates/institutional-landing/index.json-ld
> +				"en": "institutional-landing-en.html main > *:not(.pagedetails)",
This solution seems to work well.

2024-05-17 19:25 UTC, duboisp requested changes

2024-05-17 19:25 UTC, duboisp commented on templates/institutional-landing/institutional-landing-bad.html
> +<div data-ajax-replace="institutional-landing-en.html main > *:not(.pagedetails)"></div>
This dont' work. The custom JS are not triggered to fix the heading by adding the page body CSS class `page-type-ilp`

2024-05-21 14:40 UTC, duboisp requested changes
Tested and reviewed, everything look good except the change in the package.json need to be reverted.

2024-05-21 14:40 UTC, duboisp commented on package.json
> +    "wet-boew": "github:wet-boew/wet-boew#v4.0.79"
You re-added this change by mistake, please remove this file change. Thanks

2024-05-21 14:42 UTC, duboisp approved these changes
Appoved

2024-05-21 16:04 UTC, merged