Wet-boew working examples #5
wet-boew/GCWeb pull request #2365
Opened 2024-05-17 18:22 UTC by SebastianBurke

Added wet-boew working examples::

charts
details-close
dismissable-content
equalheight
exitscript
tables
wb-disable
wb-postback

2024-05-24 23:29 UTC, duboisp submitted a review, later dismissed
See the inline comments.

2024-05-24 23:29 UTC, duboisp commented on wet-boew/charts/index.json-ld
> +		"examples": [
Please add the other examples
* Customization
* Customizing pie charts
* Labels and reference values
* Specific test cases

2024-05-24 23:29 UTC, duboisp commented on wet-boew/equalheight/index.json-ld
> +		"examples": [
Missing one example, the one that use CSS grid and put it first in the JSON array.

2024-05-24 23:29 UTC, duboisp commented on wet-boew/details-close/index.json-ld
> +	"status": "stable",
Change its status to "provisional"

2024-05-24 23:29 UTC, duboisp commented on wet-boew/tables/index.json-ld
> +		"examples": [
Please add the other example: Table filter

2024-08-09 15:46 UTC, Garneauma requested changes

2024-08-09 15:46 UTC, Garneauma commented on wet-boew/charts/index.json-ld
> +				"url": "https://wet-boew.github.io/wet-boew/docs/ref/charts/charts-en.html"
```suggestion
				"url": "https://wet-boew.github.io/wet-boew/docs/ref/charts/charts-fr.html"
```

2024-08-09 15:46 UTC, Garneauma commented on wet-boew/details-close/index.json-ld
> +		"en": "Detail closed",
```suggestion
		"en": "Details closed",
```

2024-08-09 15:46 UTC, Garneauma commented on wet-boew/details-close/index.json-ld
> +				"title": "Detail closed",
```suggestion
				"title": "Details closed",
```

2024-08-09 15:46 UTC, Garneauma commented on wet-boew/details-close/index.json-ld
> +				"title": "Details fermée",
```suggestion
				"title": "Details fermé",
```

2024-08-09 15:46 UTC, Garneauma commented on wet-boew/details-close/index.json-ld
> +		"fr": "Details fermée"
```suggestion
		"fr": "Details fermé"
```

2024-08-09 15:46 UTC, Garneauma commented on wet-boew/exitscript/index.json-ld
> +		"en": "Redirects users to another sites",
```suggestion
		"en": "Redirects users to another site",
```

2024-08-09 15:46 UTC, Garneauma commented on wet-boew/tables/index.json-ld
> +		"fr": "Ajoutes des fonctionnalités aux tableaux telles que la recherche, le tri, le filtrage et la pagination"
```suggestion
		"fr": "Ajoute des fonctionnalités aux tableaux telles que la recherche, le tri, le filtrage et la pagination"
```

2024-08-09 18:01 UTC, Garneauma requested changes

2024-08-09 19:12 UTC, merged