Contributors: stabilizing component
wet-boew/GCWeb pull request #2374
Opened 2024-05-29 13:23 UTC by Garneauma

2024-06-03 14:06 UTC, Garneauma commented
Pre-approved upon successful review.

2024-06-21 20:56 UTC, duboisp requested changes
See the inline comments.


**Question for DTO:** Should we limit the width when there is long name for the institution that are take the full page width? Especially in medium view and up? Currently if the item takes more place it is moved on a new line, is that the expected behaviour?
![image](https://github.com/wet-boew/GCWeb/assets/1676030/065545c5-d1ed-48eb-ac78-f175046025ac)

2024-07-02 18:17 UTC, Garneauma commented on components/gc-contributors/_base.scss
> +		font-size: $small-size;
This is specific to this component, not to the Topic template.

2024-07-04 14:21 UTC, Garneauma commented
> See the inline comments.
> 
> **Question for DTO:** Should we limit the width when there is long name for the institution that are take the full page width? Especially in medium view and up? Currently if the item takes more place it is moved on a new line, is that the expected behaviour?

Asked DTO. The bullet should be on the right of the first item. Also, the second row should be left-aligned with the first row (not the "From:" title). Made the changes to reflect those decisions.

2024-07-19 14:46 UTC, duboisp requested changes
Can we bind the bullet with the following item instead of the preceding?

Because with a long department/agency name I do observe the following:

![image](https://github.com/user-attachments/assets/48f92d92-60d5-431b-b942-f1b70f04ab0f)

And we are missing a working example for that. May be a new sample code that you can add in the same working example page?

2024-07-19 16:02 UTC, Garneauma commented
> Can we bind the bullet with the following item instead of the preceding?
> 
> Because with a long department/agency name I do observe the following:

The current behaviour for wrapping contributors names is the one decided by DTO.

2024-07-19 18:40 UTC, duboisp approved these changes
Look good, requested change has been applied

2024-07-22 14:05 UTC, merged