Fixing geo-map
wet-boew/GCWeb pull request #2394
Opened 2024-07-11 15:29 UTC by SebastianBurke

added copy commands for the geomap config*.js files

2024-07-12 18:29 UTC, SebastianBurke commented
Abandoned the gruntfile modification and brought over the full demo to gcweb

2024-07-15 14:17 UTC, Garneauma commented
Pre-approved upon successful testing. This is only a content change.

2024-07-16 15:18 UTC, Garneauma requested changes

2024-07-16 17:35 UTC, Garneauma requested changes

2024-07-16 17:35 UTC, Garneauma commented on wet-boew/geomap/geomap-en.html
> +}
Please to the following to all 4 HTML files' front-matter:
- Please remove "category", "tag", and "parentDir".
- Rename "altLangPrefix" to "altLangPage" and add the language suffix and file extension, i.e.: "geomap-en.html"

```suggestion
{
	"title": "Geomap",
	"language": "en",
	"description": "Displays a dynamic map over which information from additional sources can be overlaid.",
	"altLangPage": "geomap-en.html",
	"js": ["demo/client_functions"],
	"dateModified": "2016-04-22"
}
```

2024-07-17 12:48 UTC, Garneauma requested changes
You did not update geomap-v4.0.30.html (en and fr).

2024-07-17 17:19 UTC, Garneauma approved these changes

2024-07-17 17:20 UTC, merged