WET-boew -> GCWeb ->Simple example pages
wet-boew/GCWeb pull request #2409
Opened 2024-08-01 16:10 UTC by SebastianBurke

ajax-fetch
json-fetch
navcurrent
resize
wb-focus

2024-08-14 15:52 UTC, Garneauma requested changes
@SebastianBurke 
- [ ] Fix the URLs to the example pages for Navcurrent and Resize (make sure the language toggle also works)
- [ ] Remove the class "list-inline" from the list of events and list of components. It is not necessary

2024-08-15 13:18 UTC, SebastianBurke commented
Made the changes @Garneauma 
I am unsure if I made all the changes you requested to Navcurrent and resize - please confirm, thanks!

2024-08-26 14:10 UTC, Garneauma commented
Pre-approved upon successful review.

2024-10-01 12:52 UTC, Garneauma reviewed
- [ ] Rename folder "navcurrent" to "wb-navcurr"
- [ ] Rename folder "resize" to "wb-rsz"
- [ ] Address inline comments

2024-10-01 12:52 UTC, Garneauma commented on wet-boew/ajax-fetch/ajax-fetch-en.html
> +</ul>
I don't believe this is necessary as they are not actual plugins. Do this for all your examples.
```suggestion
```

2025-10-01 13:53 UTC, Garneauma approved these changes

2025-10-01 14:00 UTC, merged