WET-464 -> Topic theme with stacked header
wet-boew/GCWeb pull request #2419
Opened 2024-08-20 14:09 UTC by SebastianBurke

2024-08-20 14:23 UTC, duboisp requested changes
And the following jekyll alert need to be inserted in the documentation page, at the top

```
{%- include /alert-softlaunch.html genre="m" component="topic template" version="2" -%}
```

```
{%- include /alert-softlaunch.html genre="m" component="gabarit de sujet" version="2" -%}
```

@Ricokola once the example is updated, please spin up a working example for our BA. Thanks

2024-08-20 14:23 UTC, duboisp commented on templates/topic/topic-stackedheader-en.html
This one need to become the default "topic-en.html"

And the current page "topic-en.html" need to be renamed.

2024-08-20 14:44 UTC, duboisp requested changes

2024-08-20 14:44 UTC, duboisp commented on templates/topic/topic-en.html
> +altLangPage: "topic-stackedheader-fr.html"
```suggestion
altLangPage: "topic-fr.html"
```

2024-08-20 14:44 UTC, duboisp commented on templates/topic/topic-fr.html
> +altLangPage: "topic-stackedheader-en.html"
```suggestion
altLangPage: "topic-en.html"
```

2024-08-20 14:44 UTC, duboisp commented on templates/topic/topic-nostackedheader-en.html
> +altLangPage: "topic-fr.html"
```suggestion
altLangPage: "topic-nostackedheader-fr.html"
```

2024-08-20 14:44 UTC, duboisp commented on templates/topic/topic-nostackedheader-fr.html
> +altLangPage: "topic-en.html"
```suggestion
altLangPage: "topic-nostackedheader-en.html"
```

2024-08-20 14:44 UTC, duboisp commented on templates/topic/topic-nostackedheader-fr.html
> +			<h1 property="name" id="wb-cont">{{ page.title }}</h1>
Use the include like you did for "topic-en,html"

2024-08-20 14:44 UTC, duboisp commented on templates/topic/topic-nostackedheader-en.html
> +			<h1 property="name" id="wb-cont">{{ page.title }}</h1>
Use the include like you did for "topic-en,html"

2024-08-21 12:17 UTC, Ricokola requested changes
Great work! Just few minor content changes.

2024-08-21 12:17 UTC, Ricokola commented on _data/templates.json
> +					"fr": "août 2024 - Version 1 de la variante d'en-tête empilé."
For consistency, I suggest replacing the word "empilé" by "superposé"

2024-08-21 12:17 UTC, Ricokola commented on _data/templates.json
> +				"fr": "Page de sujet avec en-tête superposée"
"en-tête" is masculine so "superposée" should not have an extra "e" at the end.

2024-08-21 12:17 UTC, Ricokola commented on _data/templates.json
> +						"text": "Page de sujet avec en-tête superposée"
"en-tête" is masculine so "superposée" should not have an extra "e" at the end.

2024-08-21 12:17 UTC, Ricokola commented on templates/topic/index.json-ld
> +				"fr": "Page de sujet avec en-tête superposée"
"en-tête" is masculine so "superposée" should not have an extra "e" at the end.

2024-08-21 12:17 UTC, Ricokola commented on templates/topic/index.json-ld
> +						"text": "Page de sujet avec en-tête superposée"
"en-tête" is masculine so "superposée" should not have an extra "e" at the end.

2024-08-21 15:21 UTC, Ricokola requested changes
I've identified few remaining content changes. Can you please confirm when they will be adjusted.

2024-08-21 15:21 UTC, Ricokola commented on _data/templates.json
> +				"title": "[Titre du sujet sans en-tête superposée]",
Can you please remove the extra "e" at the end of the following sentence: "Titre du sujet sans en-tête superposée"

2024-08-21 15:21 UTC, Ricokola commented on _data/templates.json
> +				"fr": "Page de sujet avec en-tête superposée"
Can you please remove the extra "e" at the end of the following sentence: "Titre du sujet sans en-tête superposée"

2024-08-21 15:21 UTC, Ricokola commented on _data/templates.json
> +					"fr": { "href": "topic-fr.html", "text": "Page de sujet avec en-tête superposée" }
Can you please remove the extra "e" at the end of the following sentence: "Titre du sujet sans en-tête superposée"

2024-08-21 15:21 UTC, Ricokola commented on _data/templates.json
> +				"fr": "Page de sujet avec en-tête superposée"
Can you please remove the extra "e" at the end of the following sentence: "Titre du sujet sans en-tête superposée"

2024-08-21 15:21 UTC, Ricokola commented on _data/templates.json
> +						"text": "Page de sujet avec en-tête superposée"
Can you please remove the extra "e" at the end of the following sentence: "Titre du sujet sans en-tête superposée"

2024-08-21 17:25 UTC, duboisp requested changes
The "template.json" can be simply re-generated during the release.

2024-08-27 14:17 UTC, Garneauma requested changes
Please move the variation with stacked header below the the variation without since it is no longer the default one.

2024-08-27 14:21 UTC, Garneauma requested changes

2024-08-27 14:21 UTC, Garneauma commented on templates/topic/index.json-ld
> +			"iteration": "_:iteration_topic_4",
```suggestion
			"iteration": "_:iteration_topic_3",
```

2024-08-27 14:21 UTC, Garneauma commented on templates/topic/index.json-ld
> +			"iteration": "_:iteration_topic_4",
```suggestion
			"iteration": "_:iteration_topic_3",
```

2024-08-27 15:34 UTC, Garneauma requested changes
I think that's the only thing left. Unless @duboisp sees something I don't.

2024-08-27 15:34 UTC, Garneauma commented on templates/topic/index.json-ld
> +				"fr": "Page de sujet avec en-tête superposé"
```suggestion
				"en": "Standard",
				"fr": "Standard"
```

2024-08-27 15:35 UTC, Garneauma requested changes

2024-08-27 15:35 UTC, Garneauma commented on templates/topic/index.json-ld
> +				"fr": "Page de sujet avec en-tête superposé"
```suggestion
				"en": "Standard",
				"fr": "Standard"
```

2024-08-27 16:03 UTC, Garneauma commented on templates/topic/index.json-ld
> +				"fr": "Page de sujet avec en-tête superposé"
@SebastianBurke Capital "S" please.

2024-08-27 17:34 UTC, duboisp requested changes

2024-08-27 17:34 UTC, duboisp commented on _includes/settings.liquid
Ce fichier doit être exclu

2024-08-27 17:34 UTC, duboisp commented on sites/main-page-title/_base.scss
Ce PR ne doit pas contenir les changements d'introduction du Stacked header donc ce fichier ne devrait pas être modifier

2024-08-27 17:37 UTC, duboisp requested changes
@Garneauma can you check the commit history and fix it?

2024-08-27 17:45 UTC, duboisp reviewed
Other than re-organizing the commit history, the propose change look good.

2024-08-27 19:00 UTC, Garneauma commented
WET-464 was approved by PP and DTO as of now.

2024-08-27 19:14 UTC, merged