Clean up: moving deprecated components to méli-mélo
wet-boew/GCWeb pull request #2425
Opened 2024-09-17 14:34 UTC by Garneauma

This is a clean up PR to deprecate some demoted components and move some already deprecated components to the experimentation section.

The following components/templates have been deprecated:
- Follow us, use [GC Follow us](https://wet-boew.github.io/GCWeb/components/gc-follow-us/gc-follow-us-en.html) variation instead
- Page details version 3.0 and 3.1, use [Page details version 3.2](https://wet-boew.github.io/GCWeb/sites/page-details/page-details-default-en.html) instead
- Theme and Topic template version 1, use [Topic template version 2.1](https://wet-boew.github.io/GCWeb/templates/topic/topic-en.html) instead
- Footer version 6.0, use [Footer version 7.0](https://wet-boew.github.io/GCWeb/sites/footers/no-footer-contextual-en.html) instead

The following components/theme have been moved to the experimentation section:
- Chat wizard
- Background image heading
- Light warning alert icon
- Pink day theme

Note: the Footer version 1 through 5 working examples have been removed from the codebase as they have been deprecated from more than a year. The code samples remain.

2024-11-28 05:23 UTC, duboisp requested changes
Partial and incomplete review, I only checked the follow-us deprecation

2024-11-28 05:23 UTC, duboisp commented on components/gc-follow-us/_base.scss
> -	}
Can you duplicate the code about "googleplus" into the "deprecated" méli-mélo project. So for the one that want to use it, they will be able to use the méli-mélo compilation.

I know that was already mentioned in the code, but it was never officially communicated. Thanks

2024-11-28 05:23 UTC, duboisp commented on components/gc-follow-us/_base.scss
> +// START: Deprecated as of version 16.0.0
Deprecated code should be cloned into the "deprecated" méli-mélo project.

2024-11-28 12:25 UTC, duboisp requested changes
Je pensais que les fonctionnalités provisionnelles retiré seraient tous contenu dans "deprecated". La raison principal de leur déplacement c'est parce qu'il y a eu aucune action récente démontrant l'intérêt de les stabiliser officiellement

2024-12-05 18:47 UTC, duboisp requested changes
Partial review.

We will need a note that those image file are deprecated and are going to removed from our distribution.
* x-blue-line.png

2024-12-05 18:47 UTC, duboisp commented on components/_provisional.scss
Can you add a comment, start and end, to indicate the CSS block that has been deprecated?

2024-12-05 18:47 UTC, duboisp commented on méli-mélo/deprecated/style.css
> +}
We should have a copy of all the depreceated css in gc-follow-us/_base.scss here

2024-12-05 18:47 UTC, duboisp commented on components/gc-follow-us/_base.scss
> -
Keep this here, but we should have a copy in the depreceated/style.css

2024-12-05 18:47 UTC, duboisp commented on méli-mélo/deprecated/assets/x-blue-line.png
We can not move this asset, it need to remain in our dist until it's formal removal. But please keep a copy the file in the méli-mélo deprecated.

2024-12-05 18:47 UTC, duboisp commented on méli-mélo/deprecated/chatwizard/chatwizard-en.html
You can move those working example page and only change the link that was in the index.json-ld files

2024-12-05 18:47 UTC, duboisp commented on méli-mélo/deprecated/chatwizard/chatwizard-en.html
Also, the state in the index.json-ld for Chat wizard must be updated for "Deprecated"

2024-12-05 19:21 UTC, duboisp requested changes
Partial review

2024-12-05 19:21 UTC, duboisp commented on méli-mélo/deprecated/deprecated.html
> +<h3>Working example</h3>
Remove the existing working example that we have in our current provisional page. And in the provisional page link to this deprecated page.

2024-12-05 19:21 UTC, duboisp commented on méli-mélo/deprecated/pinkday/docs-en.html
Update the link in the index.json-ld of template/thematic/pink-day.html

And delete the HTML page only that is in the template/thematic/ folder

2024-12-05 19:21 UTC, duboisp commented on méli-mélo/deprecated/pinkday/meta.md
This file can be removed as pink day are not going to be an independent experimental project

2024-12-05 20:20 UTC, duboisp commented on sites/page-details/index.json-ld
> +					"fr": { "href": "deprecated/page-details-v3-fr.html", "text": "Obsolète - Détails de la page version 3.0" }
Let's add the GCWeb version of when we deprecated that pattern. It's to ease future clean up 

```suggestion
					"en": { "href": "deprecated/page-details-v3-en.html", "text": "Deprecated as GCWeb v16.0.0 - Page details version 3.0" },
					"fr": { "href": "deprecated/page-details-v3-fr.html", "text": "Obsolète à partir de GCWeb v16.0.0 - Détails de la page version 3.0" }
```

2024-12-05 20:20 UTC, duboisp commented on sites/page-details/index.json-ld
> +					"fr": { "href": "deprecated/page-details-v3.1-fr.html", "text": "Obsolète - Détails de la page version 3.1" }
```suggestion
					"en": { "href": "deprecated/page-details-v3.1-en.html", "text": "Deprecated as GCWeb v16.0.0 - Page details version 3.1" },
					"fr": { "href": "deprecated/page-details-v3.1-fr.html", "text": "Obsolète à partir de GCWeb v16.0.0 - Détails de la page version 3.1" }
```

2024-12-05 20:22 UTC, duboisp commented on sites/page-details/deprecated/page-details-v3-fr.html
Change the word "retrogradé" in the page title for "obsolète"

2024-12-05 20:23 UTC, duboisp commented on sites/page-details/deprecated/page-details-v3.1-en.html
Change the word "demoted" in the page title for "deprecated"

2024-12-05 20:23 UTC, duboisp commented on sites/page-details/deprecated/page-details-v3.1-fr.html
Change the word "retrogradé" in the page title for "obsolète"

2024-12-05 20:26 UTC, duboisp commented on templates/institutional-landing/reports/a11y-1.json
> +    "dct:references": "https://wet-boew.github.io/GCWeb/templates/institutional-landing/deprecated/institution-landing-en.html",
Don't update the link in the accessibility report. They are not designed to be maintainable content but more to reflect the state at that specific moment of time of when the report was created.

```suggestion
    "dct:references": "https://wet-boew.github.io/GCWeb/templates/institutional-landing/demoted/institution-landing-en.html",
```

2024-12-05 20:30 UTC, duboisp commented on templates/topic/index.json-ld
>  						"text": "Theme - Topic page version 2 (beta)"
We are missing a change set to hold the state of those iteration.

For now, let update the title and clearly indicate they are deprecated.

```suggestion
						"href": "deprecated/theme-topic-en.html",
						"text": "Deprecated as GCWeb v16.0.0 - Theme - Topic page version 2 (beta)"
```

2024-12-05 22:13 UTC, duboisp requested changes
A few little content adjustment and some change for the CSS copied over the deprecated css file.

2024-12-05 22:13 UTC, duboisp commented on templates/topic/index.json-ld
> +				"title": "Theme/Topic page - Deprecated",
```suggestion
				"title": "Theme/Topic page - Deprecated as GCWeb v16",
```

2024-12-05 22:13 UTC, duboisp commented on templates/topic/index.json-ld
> +				"title": "Page de sujet/thème - Obsolète",
```suggestion
				"title": "Page de sujet/thème - Obsolète à partir de GCWeb v16",
```

2024-12-05 22:13 UTC, duboisp commented on templates/topic/index.json-ld
> +				"title": "Sujet de plus bas niveau (avec une navigation secondaire) - Obsolète",
```suggestion
				"title": "Sujet de plus bas niveau (avec une navigation secondaire) - Obsolète à partir de GCWeb v16",
```

2024-12-05 22:13 UTC, duboisp commented on templates/topic/index.json-ld
>  				"title": "Lowest topic (with secondary navigation) - Deprecated",
```suggestion
				"title": "Lowest topic (with secondary navigation) - Deprecated as GCWeb v16",
```

2024-12-05 22:13 UTC, duboisp commented on templates/topic/index.json-ld
>  						"text": "Topic page version 1"
```suggestion
						"href": "deprecated/topic-en.html",
						"text": "Deprecated as of GCWeb v16 - Topic page version 1"
```

2024-12-05 22:13 UTC, duboisp commented on templates/thematic/index.json-ld
> +				"title": "Pink Day",
```suggestion
				"title": "Pink Day - Deprecated as of GCWeb v16",
```

2024-12-05 22:13 UTC, duboisp commented on templates/thematic/index.json-ld
>  				"title": "Pink Day",
```suggestion
				"title": "Pink Day - Deprecated as of GCWeb v16",
```

2024-12-05 22:13 UTC, duboisp commented on templates/thematic/index.json-ld
>  				"title": "Pink Day - Home",
```suggestion
				"title": "Pink Day - Home - Deprecated as of GCWeb v16",
```

2024-12-05 22:13 UTC, duboisp commented on templates/thematic/index.json-ld
>  				"title": "Journée rose - Accueil",
```suggestion
				"title": "Journée rose - Accueil - Obsolète à partir de GCWeb v16",
```

2024-12-05 22:13 UTC, duboisp commented on templates/thematic/index.json-ld
>  				"title": "Journée rose",
```suggestion
				"title": "Journée rose - Obsolète à partir de GCWeb v16",
```

2024-12-05 22:13 UTC, duboisp commented on templates/thematic/index.json-ld
> +				"title": "Journée rose",
```suggestion
				"title": "Journée rose - Obsolète à partir de GCWeb v16",
```

2024-12-06 13:31 UTC, Garneauma commented on components/gc-follow-us/_base.scss
> -
I thought it was already deprecated, so we were at the step of removing it.

2024-12-06 19:25 UTC, duboisp approved these changes
Reviewed and tested locally. Everything look good.

@ouafaaetta note this PR do impact a lot of component/feature and provisional feature. Take the time to get the full list.

This is major change as it mark a few component as "Deprecated" and it remove the support for the old site footer which was deprecated a year and half ago.

2024-12-06 19:33 UTC, merged