Feedback area: adding a11y assessment performed by CRA
wet-boew/GCWeb pull request #2433
Opened 2024-10-18 16:52 UTC by Garneauma

2024-10-22 19:56 UTC, duboisp requested changes
See inline comments

2024-10-24 15:06 UTC, Garneauma commented on sites/feedback/reports/a11y-3.json
> +            "@type": "xsd:anyURI",
The document from CRA refers to this image as "OS Magnification".

2024-11-04 17:00 UTC, duboisp requested changes
See inline comments.

I suggest in parenthesis to indicate the slide number in the presentation that are matching the item.

2024-11-04 17:00 UTC, duboisp commented on sites/feedback/reports/a11y-3.json
> +            "@value": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABaEAAAalCAYAAAAmRwTYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAFxEAABcRAcom8z8AAP+lSURBVHhe7N0JnI1l/wbwe/YxizGDwawYxr7ve1
That property `selected` is noise added by my prototype tool, please remove.

2024-11-04 20:13 UTC, duboisp approved these changes
Looks good, but there is some additional comments at the end, should we include those?

2024-11-04 20:27 UTC, merged

2024-11-04 20:27 UTC, duboisp commented
Note: Ceci est seulement du contenu.