wb-tables  DataTable Utilities
wet-boew/GCWeb pull request #2438
Opened 2024-10-24 10:29 UTC by bozzit

Utility Plugin that adds data formatting options and Table Totals

as Per Documentation: https://bozzit.github.io/GCWeb/m%C3%A9li-m%C3%A9lo/2024-10-datatable-utilities/index-eng.html

2024-10-28 14:20 UTC, Garneauma commented
Pre-approved upon successful review and passing of the méli-mélo checklist.

To do (for WET-BOEW team):
 - Create `meta.md` file
 - Create permanent URL

2024-10-31 14:57 UTC, Garneauma requested changes
Thank you for your contribution @bozzit ! Below are a few comments and suggestions:
- [ ] Please remove all debug messages (or comment out).
- [ ] Please rename `index-eng.html` to `index-en.html` and `index-fra.html` to `index-fr.html` to keep it consistent with the rest of the project.
- [ ] Suggestion: create a separate documentation page for all the options instead of having them in the JS file. You could follow the table under "Configuration options" in the [Fieldflow component](https://wet-boew.github.io/GCWeb/components/wb-fieldflow/fieldflow-doc-en.html). No need to have it translated.
- [x] Please add an implementation plan item: "Produce accessibility conformance report".
- [x] I don't see a working example for the following option: `wb-col-cur-thousand`.

2024-10-31 18:04 UTC, bozzit commented
for Debug messages you mean : debugMsg(... ?  Those only get printed IF you pass   data-wb-tables-utility="{"debug":true, to the component.  I can amend the example to not use debug: true if you wish but I believe that having the ability to print debug messages on demand is a nice to have. 

Let me know

2024-11-01 14:49 UTC, Garneauma commented
> for Debug messages you mean : debugMsg(... ? Those only get printed IF you pass data-wb-tables-utility="{"debug":true, to the component. I can amend the example to not use debug: true if you wish but I believe that having the ability to print debug messages on demand is a nice to have.
> 
> Let me know

OK no problem about the debug messages. Sorry did not notice it was only with that option.

2024-11-01 16:04 UTC, bozzit commented
So once I have made the requested Changes, how do I go about submitting the changes?  New Pull request? OR is there a way to update it?

2024-11-01 18:06 UTC, Garneauma commented
@bozzit You should make your changes locally. Then, you can amend your previous commit and force-push to your remote branch:
- `git add .`
- `git commit --amend --no-edit`
- `git push -f origin master`

2024-11-04 16:46 UTC, Garneauma requested changes
@bozzit Thank you for creating the documentation page and for taking the time to translate it! I have highlighted some changes to keep it consistent with the rest of the GCWeb documentation and some small typos.

Note: not mandatory, but every instance of "Table" in French should be changed to "Tableau".

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-en.html
> +<div>
I don't believe this div should be there.
```suggestion
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-en.html
> +    <a href="index-en.html">Back</a>
```suggestion
    <h2>Working examples</h2>
    <ul>
        <li><a href="index-en.html">DataTables utilities</a></li>
    </ul>
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-en.html
> +    <p>Document the public configuration options that can be used by implementers or developers.</p>
Please remove this paragraph.
```suggestion
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-en.html
> +                <td>When applied to a column, a column footer total is calcualted</td>
Just to keep it consistent.
```suggestion
                <td>When this class is applied to a column, a column footer total is calculated</td>
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-fr.html
> +title: DataTable Utilities - Documentation
```suggestion
title: Utilitaires DataTables - Documentation
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-fr.html
> +description: Utility to Manipulate JSON Data.
```suggestion
description: Liste d'utilitaires permettant la modification de tableaux DataTables.
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-en.html
> +description: Utility to Manipulate JSON Data.
```suggestion
description: List of utilities to manipulate DataTables tables.
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-fr.html
> +<div>
```suggestion
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-fr.html
> +    <a href="index-fr.html">retour</a>
```suggestion
    <h2>Exemples pratiques</h2>
    <ul>
        <li><a href="index-fr.html">Utilitaires DataTables</a></li>
    </ul>
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-fr.html
> +	<h2>Configuration options</h2>
```suggestion
	<h2>Options de configuration</h2>
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-fr.html
> +	<p>Document the public configuration options that can be used by implementers or developers.</p>
```suggestion
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-fr.html
> +	<table class="table">
```suggestion
	<table class="table" lang="en">
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-fr.html
> +	<p>Enable the plugin for the Target Table by adding wb-tables-utility to the &lt;table&gt; element <code>&lt;table class=&quot;table wb-tables wb-tables-utility&quot;&gt; data-wb-tables-utility=&quo
```suggestion
	<p>Activez le plugiciel pour le tableau ciblé en ajoutant la classe CSS <code>wb-tables-utility</code> au tableau. Ajoutez l'attribut <code>data-wb-tables-utility</code> pour configurer les options.</p>
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-en.html
> +    <p>Enable the plugin for the Target Table by adding wb-tables-utility to the &lt;table&gt; element <code>&lt;table class=&quot;table wb-tables wb-tables-utility&quot;&gt; data-wb-tables-utility=&
```suggestion
   <p>Enable the plugin for the targeted table by adding the CSS class <code>wb-tables-utility</code> to the table. Add the attribute <code>data-wb-tables-utility</code> to configure the options.</p>
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-fr.html
> +				<td>When applied to a column, a column footer total is calcualted</td>
```suggestion
				<td>When this class is applied to a column, a column footer total is calculated</td>
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/index-en.html
> +---
```suggestion
---
<p><a href="datatable-utilities-doc-en.html" class="btn btn-primary">Documentation</a></p>
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/index-en.html
> +<p>Sponsor: PSPC - {{ implPlan.sponsor }}</p>
Since there is a documentation page now. Could you please move this to the documentation page?

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/index-en.html
> +</div>
```suggestion
<h2 class="panel-title">On this page</h2>
<ul>
    <li><a href="#a1">Control Table with Raw Data</a></li>
     <li><a href="#a2">Column Data Manipulation Example 1</a></li>
    <li><a href="#a3">Column Data Manipulation Example 2</a></li>
    <li><a href="#a4">Table Footer With Static Totals</a></li>
    <li><a href="#a5">Table Footer With Dynamic Totals updated when Filtered</a></li>
</ul>
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/index-fr.html
> +</div>
```suggestion
<h2 class="panel-title">Sur cette page</h2>
<ul>
    <li><a href="#a1">Table de contrôle avec données brute</a></li>
    <li><a href="#a2">Exemple 1 de manipulation des données de colonne</a></li>
    <li><a href="#a3">Exemple 2 de manipulation des données de colonne</a></li>
    <li><a href="#a4">Pied de page de table avec totaux statiques</a></li>
    <li><a href="#a5">Pied de page de table avec totaux dynamiques mis à jour lors du filtrage</a></li>
</ul>
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/index-fr.html
> +<p>Commanditaire : SPAC - {{ implPlan.sponsor }}</p>
Please move this to the documentation page.

```suggestion
```

2024-11-04 16:46 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/index-fr.html
> +---
```suggestion
---

<p><a href="datatable-utilities-doc-fr.html" class="btn btn-primary">Documentation</a></p>
```

2024-11-04 17:04 UTC, bozzit commented
I think I got them all, but let me know if I missed or messed something up

2024-11-04 19:31 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/index-en.html
> +<h2 class="panel-title">On this page</h2>
```suggestion
<h2>On this page</h2>
```

2024-11-04 19:31 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/index-en.html
> +<div class="mrgn-bttm-lg">
```suggestion
```

2024-11-04 19:41 UTC, Garneauma requested changes
@bozzit You missed a few. I have added some other ones.

2024-11-04 19:41 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/index-en.html
> +---
```suggestion
---

<div class="wb-prettify all-pre hide"></div>

```

2024-11-04 19:41 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/index-fr.html
> +<h2 class="panel-title">Sur cette page</h2>
```suggestion
<h2>Sur cette page</h2>
```

2024-11-04 19:41 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/index-fr.html
> +---
```suggestion
---

<div class="wb-prettify all-pre hide"></div>

```

2024-11-04 19:41 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/index-fr.html
> +<div class="mrgn-bttm-lg">
```suggestion
```

2024-11-04 19:41 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/index-en.html
> +---
@bozzit You did not add this button. Do in French and English.

2024-11-04 19:41 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/meta.md
> +  - •	Envisager d'ajouter d'autres classes de manipulation de données (pourcentage)?
```suggestion
  - Envisager d'ajouter d'autres classes de manipulation de données (pourcentage)?
```

2024-11-04 19:41 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-fr.html
> +<h2>Examples</h2>
```suggestion
<h2>Exemples pratiques</h2>
```

2024-11-04 19:41 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-fr.html
> +    <a href="index-fr.html">retour</a>
@bozzit This one was missed.

2024-11-04 19:41 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-fr.html
> +	<table class="table">
@bozzit This one was missed.

2024-11-04 19:41 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-fr.html
> +	<p>Enable the plugin for the Target Table by adding wb-tables-utility to the &lt;table&gt; element <code>&lt;table class=&quot;table wb-tables wb-tables-utility&quot;&gt; data-wb-tables-utility=&quo
@bozzit This one was missed.

2024-11-04 19:41 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/datatable-utilities-doc-en.html
> +    <p>Enable the plugin for the Target Table by adding wb-tables-utility to the &lt;table&gt; element <code>&lt;table class=&quot;table wb-tables wb-tables-utility&quot;&gt; data-wb-tables-utility=&
@bozzit This one was missed.

2024-11-04 19:41 UTC, Garneauma commented on méli-mélo/2024-10-datatable-utilities/index-fr.html
> +---
@bozzit This one was missed.

2024-11-04 20:30 UTC, bozzit commented
Maybe email me the change files ? I’ll take a look at it in the morning.

2024-11-05 13:48 UTC, Garneauma commented
@bozzit The unresolved conversations are the only changes left to do. Please make sure to reveal hidden conversations by clicking the "Load more..." button.
Here's the list:
 - Add `lang="en"` on French documentation table.
 - Update paragraph above configuration table in both languages.
 - Remove useless `<div class="mrgn-bttm-lg">` wrapping the first example in both languages.

I will then do a final review, but I think that's it!

2024-11-05 15:09 UTC, Garneauma approved these changes
Approved! Thank you for your contribution @bozzit.

Could you please update your PR comment (the one at the top of the page) to include the following (no need to be very detailed):
- Clear and simple explanation of the new feature;
- The impact on the sponsored department;
- The impact on the public.

2024-11-05 16:07 UTC, bozzit commented
I thought I included this in the text at the top:

DataTable Utilities, includes Data Manipulation Classes for emails, Urls and Money. Also Includes Datatable Footer Totals. 

Having this plugin integrated will make the transition to Canada.ca easier as these features are already in use on https://www.tpsgc-pwgsc.gc.ca, currently some of the pages that make use of this plugin and other pages that make use of Other JavaScripts are just pointed to from Canada.ca

The Public at Large, the plugin makes DataTables more user friendly with Clickable Links, and they are used to this functionality our PRE Canada.ca Pages.

2024-11-05 16:50 UTC, merged