Release v15.7.1
wet-boew/GCWeb pull request #2443
Opened 2024-11-07 22:36 UTC by ouafaaetta

Release v15.7.1

2024-11-08 16:54 UTC, ouafaaetta commented on méli-mélo/compilation-gelé/index-en.md
> +	- 2023-10-clipboard [as of GCWeb v14.7.0](https://github.com/wet-boew/GCWeb/tree/v15.7.0/m%C3%A9li-m%C3%A9lo/2023-10-clipboard)
C'est fait

2024-11-08 20:58 UTC, duboisp requested changes
See my inline comments

2024-11-08 20:58 UTC, duboisp commented on méli-mélo/compilation-gelé/index-en.md
>  altLangPage: "méli-mélo-fr.html"
```suggestion
altLangPage: "index-fr.html"
```

Et faire le même changement équivalent pourla page française.

2024-11-08 20:58 UTC, duboisp commented on méli-mélo/compilation-gelé/index-en.md
> +	- deprecated[as of GCWeb v15.7.0](https://github.com/wet-boew/GCWeb/tree/v15.7.0/m%C3%A9li-m%C3%A9lo/deprecated)
Il manque une espace avant le lien

```suggestion
	- 2023-09-distance-calculator [as of GCWeb v15.7.0](https://github.com/wet-boew/GCWeb/tree/v15.7.0/m%C3%A9li-m%C3%A9lo/2023-09-distance-calculator)
	- 2023-09-collection-sort [as of GCWeb v15.7.0](https://github.com/wet-boew/GCWeb/tree/v15.7.0/m%C3%A9li-m%C3%A9lo/2023-09-collection-sort)
	- 2021-05-steps [as of GCWeb v15.7.0](https://github.com/wet-boew/GCWeb/tree/v15.7.0/m%C3%A9li-m%C3%A9lo/steps)
	- 2024-04-stepsquiz [as of GCWeb v15.7.0](https://github.com/wet-boew/GCWeb/tree/v15.7.0/m%C3%A9li-m%C3%A9lo/2024-04-stepsquiz)
	- 2024-02-charts [as of GCWeb v15.7.0](https://github.com/wet-boew/GCWeb/tree/v15.7.0/m%C3%A9li-m%C3%A9lo/2024-02-charts)
	- deprecated [as of GCWeb v15.7.0](https://github.com/wet-boew/GCWeb/tree/v15.7.0/m%C3%A9li-m%C3%A9lo/deprecated)
```

2024-11-08 20:58 UTC, duboisp commented on méli-mélo/compilation-gelé/index-fr.md
> +	- deprecated[as of GCWeb v15.7.0](https://github.com/wet-boew/GCWeb/tree/v15.7.0/m%C3%A9li-m%C3%A9lo/deprecated)
Il manque une espace avant le lien

```suggestion
	- 2023-09-distance-calculator [as of GCWeb v15.7.0](https://github.com/wet-boew/GCWeb/tree/v15.7.0/m%C3%A9li-m%C3%A9lo/2023-09-distance-calculator)
	- 2023-09-collection-sort [as of GCWeb v15.7.0](https://github.com/wet-boew/GCWeb/tree/v15.7.0/m%C3%A9li-m%C3%A9lo/2023-09-collection-sort)
	- 2021-05-steps [as of GCWeb v15.7.0](https://github.com/wet-boew/GCWeb/tree/v15.7.0/m%C3%A9li-m%C3%A9lo/steps)
	- 2024-04-stepsquiz [as of GCWeb v15.7.0](https://github.com/wet-boew/GCWeb/tree/v15.7.0/m%C3%A9li-m%C3%A9lo/2024-04-stepsquiz)
	- 2024-02-charts [as of GCWeb v15.7.0](https://github.com/wet-boew/GCWeb/tree/v15.7.0/m%C3%A9li-m%C3%A9lo/2024-02-charts)
	- deprecated [as of GCWeb v15.7.0](https://github.com/wet-boew/GCWeb/tree/v15.7.0/m%C3%A9li-m%C3%A9lo/deprecated)
```

2024-11-08 20:58 UTC, duboisp commented on docs/méta-détails/2024-10-datatable-utilities-fr.html
> +componentName: 2021-05-steps
```suggestion
componentName: 2024-10-datatable-utilities
```

2024-11-08 20:58 UTC, duboisp commented on _data/méli-mélo.json
Il faut ajouter le nouveau projet expérimental dans la list "subProject"

2024-11-08 20:58 UTC, duboisp commented on _data/méli-mélo.json
> +			    "2024-02-charts",
Il faut ajouter "2024-10-datatabale-utilities" dans nahanni

2024-11-08 21:35 UTC, ouafaaetta commented on _data/méli-mélo.json
done

2024-11-08 22:10 UTC, duboisp requested changes
See my inline comments

2024-11-08 22:10 UTC, duboisp commented on _data/méli-mélo.json
> +			"mainpage": "index.html"
la page principale du projet est:

```suggestion
			"mainpage": "index-en.html"
```

2024-11-08 22:10 UTC, duboisp commented on méli-mélo/2024-10-datatable-utilities/meta.md
Il faudrait compléter la liste des pages définie à la ligne 20

```
pages:
  examples:
    - title: DataTable Utilities
      language: en
      path: index-en.html
    - title: Utilitaire DataTable
      language: fr
      path: index-fr.html
  documentation:
    - title: DataTable Utilities - Documentation
      language: en
      path: datatable-utilities-doc-en.html
    - title: Utilitaire DataTable - Documentation
      language: fr
      path: datatable-utilities-doc-fr.html
```

2024-11-12 15:08 UTC, ouafaaetta commented on _data/méli-mélo.json
> +			"mainpage": "index.html"
Done

2024-11-12 18:30 UTC, duboisp reviewed
Look good, reviewed and tested locally.

One thing left, is to update the WET-BOEW version.

I will wait for the inclusion of the WET-BOEW minor version as discussed this morning

2024-11-12 20:41 UTC, duboisp approved these changes
Look good,

I also tested locally a old version but only some typo + wet-boew version was updated.

2024-11-12 20:41 UTC, duboisp commented on méli-mélo/2024-10-datatable-utilities/meta.md
fixed

2024-11-12 20:41 UTC, merged