Most requested: display items in columns
wet-boew/GCWeb pull request #2446
Opened 2024-11-19 21:03 UTC by Garneauma

This PR changes the distribution of Most requested items from top to bottom and from left to right instead of from left to right and top to bottom.

Before:
1 2
3 4
5 6

After:
1 4
2 5
3 6

2025-01-15 13:42 UTC, duboisp commented on components/gc-most-requested/_screen-lg-min.scss
> +div:not(.container) .gc-most-requested {
This don't seem to work as expected. I moved the "gc-most-requested" inside a component and the style was still applied.

Also, I am unable to observe the effect of that style in FF neither in Chrome. What it does? Should we add an additional working example for that edge case?

2025-01-15 14:04 UTC, duboisp requested changes

2025-01-15 14:04 UTC, duboisp commented on components/gc-most-requested/_screen-lg-min.scss
> +div:not(.container) .gc-most-requested {
```suggestion
:not(.container) .gc-most-requested {
```

2025-01-15 14:12 UTC, duboisp requested changes

2025-01-15 14:12 UTC, duboisp commented on components/gc-most-requested/_screen-lg-min.scss
> +div:not(.container) .gc-most-requested {
Alternatively, you can add a style to break bad implementation like undo:
* the h2 float
* col-count set to 1
* No background color.

CSS selector sample: `.container .gc-most-request`

2025-01-28 16:02 UTC, Garneauma commented
> **This change is very perceptible** and I do evaluate if as a major change because of the visual change. Additional communication might be required prior to apply this change.

In my opinion this is more a minor change than a major one. "Minor change: The change are noticeable and complement, add to the user experience and remain at least understandable as it was prior." I don't believe a user would be lost because some items have changed in order. It might be even more understandable for a user now, and easier to coomprehend for an author. We can discuss this further.

2025-03-21 12:52 UTC, duboisp commented
We received a confirmation to move ahead. Yes this change is perceptible and an user will notice that change but it don't change the component essential behaviour. So this is a Minor change.

Note: I am going to do a last PR review.

2025-05-08 18:26 UTC, duboisp requested changes
Reviewed and tested, do work as expected. There is only a little adjustment to do at the documentation.

Review checklist:

* [x] feature integration - look good
* [x] documentation - All good except the following:
  * [ ] Change/update the history date to be closer to today
  * [ ] Describe/add the minor change justification
* [x] code - Completed and look good
* [x] technical test - Completed and pass
* [x] functional check - Completed
* [x] versioning impact - This is a minor change for the most-requested component
* [x] maintenance plan - Nothing to note
* [x] Previous comment/concerns - Was all addressed

2025-05-08 18:26 UTC, duboisp commented on components/gc-most-requested/index.json-ld
> +			],
Can you change this for an "addition" and append the justification that I wrote in the Github PR about why this is a mino change. Thanks

2025-05-08 18:26 UTC, duboisp commented on components/gc-most-requested/index.json-ld
> +					"fr": "Novembre 2024 - Les items sont maintenant distribués verticalement plutôt que horizontalement."
Let's update that date for like May 2025 which is closer to the reality, or you can add an additional item and prepend "Draft" to this item

2025-05-08 19:48 UTC, duboisp approved these changes
The documentation change was applied as requested.

The CSS/JS don't seem to have modified since my last review, so I maintain my previous review as is. I did a quick functional check and it still work as expected.

2025-05-12 12:36 UTC, merged