Theme: Fix placeholder image references
wet-boew/GCWeb pull request #2448
Opened 2024-11-25 23:30 UTC by EricDunsworth

Some of GCWeb's code samples from recent years were referencing placeholder images from [placeholder.com](https://placeholder.com/) and [placehold.it](https://www.placeholder.com/). But those sites underwent changes in ownership in March 2023 and consequently ceased serving placeholder images.

This deals with it by replacing all references to via.placeholder.com and placehold.it with dummyimage.com (and swaps ? characters with & where custom text is specified to fit the latter's URL writing scheme).

GCWeb has historically used [dummyimage.com](https://dummyimage.com/) and that site still exists to this day.

Left the following references to [placeholder.com](https://placeholder.com/) "as-is" in the following WCAG assessments since they're meant to represent specific points in time:
* [templates/institutional-landing/reports/a11y-1.json](https://github.com/wet-boew/GCWeb/blob/master/templates/institutional-landing/reports/a11y-1.json)
* [templates/institutional-landing/reports/a11y-2.json](https://github.com/wet-boew/GCWeb/blob/master/templates/institutional-landing/reports/a11y-2.json)

2024-12-02 15:44 UTC, EricDunsworth commented on design-patterns/gc-intro/index.json-ld
Just so these are noted...
* This file's changes don't currently add an extra iteration for the revised example... might try force-pushing an update to add it at some point
* I'm unsure if docs examples are supposed to contain full image URLs (could've sworn I saw some others out there that used something along the lines of ``src="[your-image]"`` instead of a placeholder URL)

2024-12-02 16:04 UTC, Garneauma commented on design-patterns/gc-intro/index.json-ld
The dummy images URL aren't part of the API, so no need to create an iteration.

2024-12-04 16:43 UTC, Garneauma requested changes

2024-12-04 16:43 UTC, Garneauma commented on design-patterns/gc-intro/index.json-ld
> +				},
Please remove this history item.

2024-12-05 14:43 UTC, EricDunsworth commented on design-patterns/gc-intro/index.json-ld
> +				},
Done :).

2024-12-05 14:47 UTC, Garneauma approved these changes

2024-12-05 14:50 UTC, merged