Byline: adding documentation, moving to main title
wet-boew/GCWeb pull request #2452
Opened 2024-12-11 21:18 UTC by Garneauma

- Adding byline documentation so that it can be deprecated
- Adding "Main page title with byline" variation to the Main page title (this variation is limited to news pages on Canada.ca)

2024-12-11 21:21 UTC, Garneauma commented
@duboisp I have set the status of the byline component to deprecated. However, if we want to get this pull request out without triggering a major release, I can change it to demoted instead.

2024-12-23 15:09 UTC, Garneauma commented
Pre-approved upon successful review.

2025-01-15 21:21 UTC, duboisp requested changes
See my comment inline.

Note: We will need to discuss if we apply that by default to the last paragraph in the hgroup or if we require this to be activated by the author by using a CSS class. The second option will allow us to use the paragraph under the h1 for something else considering that the trial currently is to remove the byline.

2025-01-15 21:21 UTC, duboisp commented on components/byline/index.json-ld
> +			"status": "deprecated",
```suggestion
			"status": "demoted",
```

2025-01-15 21:21 UTC, duboisp commented on components/byline/index.json-ld
> +			"status": "deprecated",
```suggestion
			"status": "demoted",
```

2025-01-15 21:21 UTC, duboisp commented on sites/main-page-title/includes/main-page-title.html
> +	{%- endif -%}
Do we make it default or should we make the author to enable this, like by using the gc-byline class on the last paragraph?

We just need to think long term, do we want to lock down the last paragraph for a byline that is now half demote and still alive on news pages knowing that there is an intention to get it replaced by `gc-contributor` instead. Let have an internal discussion about it. 

cc @Ricokola 

I do think we should have something like to allow us to re-use that last paragraph in the "hgroup" heading section for other purpose:

```suggestion
	{%- if page.byline -%}
	<p class="gc-byline">{% if page.language == "fr" %}De&nbsp;:{% else %}From:{% endif %} <a href="{{ page.byline.url }}">{{ page.byline.institution }}</a></p>
	{%- endif -%}
```

or 

```suggestion
<hgroup class="with-byline">
  ....
	{%- if page.byline -%}
	<p>{% if page.language == "fr" %}De&nbsp;:{% else %}From:{% endif %} <a href="{{ page.byline.url }}">{{ page.byline.institution }}</a></p>
	{%- endif -%}
</hgroup>
```

2025-01-15 21:21 UTC, duboisp commented on sites/main-page-title/_base.scss
> +	p:last-child {
See the inner comment in the main-page-title include file

```suggestion
	&with-byline p:last-child {
```


```suggestion
	p:last-child.gc-byline {
```

2025-01-15 21:21 UTC, duboisp commented on sites/main-page-title/index.json-ld
> +				"title": "Main page title with byline",
Let's mention this is context specific to news article

```suggestion
				"title": "Main page title with byline for news articles",
```

2025-01-15 21:21 UTC, duboisp commented on sites/main-page-title/index.json-ld
> +				"title": "Titre principal avec institution responsable",
```suggestion
				"title": "Titre principal avec institution responsable pour les article de nouvelles",
```

2025-01-15 21:21 UTC, duboisp commented on sites/main-page-title/index.json-ld
> +				"fr": "Titre principal avec institution responsable"
```suggestion
				"en": "Main page title with byline for news articles",
				"fr": "Titre principal avec institution responsable pour les article de nouvelles"
```

2025-02-10 16:24 UTC, duboisp requested changes
See inline comments

2025-02-10 16:24 UTC, duboisp commented on sites/main-page-title/includes/main-page-title.html
> +	<p>{% if page.language == "fr" %}De&nbsp;:{% else %}From:{% endif %} <a href="{{ page.byline.url }}">{{ page.byline.institution }}</a></p>
The by-line wasn't bolded as expected when I tested

```suggestion
	<p class="gc-byline">{% if page.language == "fr" %}De&nbsp;:{% else %}From:{% endif %} <a href="{{ page.byline.url }}">{{ page.byline.institution }}</a></p>
```

2025-02-10 16:24 UTC, duboisp commented on sites/main-page-title/main-page-title-byline-en.html
> +	&lt;p>From: &lt;a href="https://www.canada.ca/en/employment-social-development/corporate/portfolio/service-canada.html">Service Canada&lt;/a>&lt;/p>
```suggestion
	&lt;p class="gc-byline">From: &lt;a href="https://www.canada.ca/en/employment-social-development/corporate/portfolio/service-canada.html">Service Canada&lt;/a>&lt;/p>
```

2025-02-10 16:24 UTC, duboisp commented on sites/main-page-title/main-page-title-byline-fr.html
> +	&lt;p>From: &lt;a href="https://www.canada.ca/fr/emploi-developpement-social/ministere/portefeuille/service-canada.html">Service Canada&lt;/a>&lt;/p>
```suggestion
	&lt;p class="gc-byline">From: &lt;a href="https://www.canada.ca/fr/emploi-developpement-social/ministere/portefeuille/service-canada.html">Service Canada&lt;/a>&lt;/p>
```

2025-02-10 16:24 UTC, duboisp commented on components/byline/index.json-ld
> +					"fr": { "href": "../../templates/content-page/content-fr.html", "text": "Page de contenu (institution responsable sous le titre principal)" }
Note: Dans un autre PR ou ici, il va falloir mettre à jour GCWeb pour que les page d’exemple courante n'utilise pas de code rétrogradé.

cc @Ricokola pour ton attention, action et coordination.

2025-02-10 16:24 UTC, duboisp commented on components/byline/index.json-ld
> +					"fr": "WET-BOEW 4 - Implémentation initiale pde la composante."
To do: Adjust the date to match the documented iteration.

En fait, il a été initialement ajouté en 2016 avec le gabarit "Complex Service" et qui est devenu très rapidement le gabarit "Advanced service".

2025-02-10 16:24 UTC, duboisp commented on sites/main-page-title/index.json-ld
> +						"code":	"<hgroup id=\"wb-cont\">\n\t<h1>Main page title</h1>\n\t<p>From: <a href=\"https://www.canada.ca/en/employment-social-development/corporate/portfolio/service-canada.html\">Service Canad
```suggestion
						"code":	"<hgroup id=\"wb-cont\">\n\t<h1>Main page title</h1>\n\t<p class="gc-byline">From: <a href=\"https://www.canada.ca/en/employment-social-development/corporate/portfolio/service-canada.html\">Service Canada</a></p>\n</hgroup>"
```

2025-02-10 16:24 UTC, duboisp commented on sites/main-page-title/index.json-ld
> +						"code":	"<hgroup id=\"wb-cont\">\n\t<h1>Titre principal</h1>\n\t<p>De&nbsp;: <a href=\"https://www.canada.ca/fr/emploi-developpement-social/ministere/portefeuille/service-canada.html\">Service
```suggestion
						"code":	"<hgroup id=\"wb-cont\">\n\t<h1>Titre principal</h1>\n\t<p class="gc-byline">De&nbsp;: <a href=\"https://www.canada.ca/fr/emploi-developpement-social/ministere/portefeuille/service-canada.html\">Service Canada</a></p>\n</hgroup>"
```

2025-02-10 16:24 UTC, duboisp commented on sites/main-page-title/index.json-ld
> +			"detectableBy": "hgroup#wb-cont > h1 + p:last-child",
```suggestion
			"detectableBy": "hgroup#wb-cont > h1 + p.gc-byline",
```

2025-02-10 16:24 UTC, duboisp commented on sites/main-page-title/index.json-ld
> +					"fr": "2024-12 - Implémentation initiale de la variation."
Ajoute une mention que ce pattern est le successeur du "component/byline" rétrograté. Ca peut être spécifié dans le même history item.

2025-02-18 14:54 UTC, duboisp approved these changes
Reviewed and tested locally, 

Looks good and work as expected.

2025-02-18 15:01 UTC, duboisp commented
Waiting for final internal approval prior to merge this.

2025-02-18 15:46 UTC, Garneauma commented
Minor - Institutional byline: adding documentation and demoting component
Minor - Main page title: adding main page title with institutional byline pattern

2025-02-18 15:46 UTC, merged