News: updating news template
wet-boew/GCWeb pull request #2458
Opened 2024-12-19 21:01 UTC by Garneauma

- Updating paragraphs above and below the news table.
- Adding instructions on what to do in basic HTML mode.

2024-12-23 15:08 UTC, Garneauma commented
Pre-approved upon successful review and approval by the News team.

2025-01-15 13:19 UTC, duboisp requested changes
Wait for @Ricokola check

2025-01-15 16:33 UTC, Ricokola commented on templates/news/news-en.html
> +			<p class="text-center nojs-hide"><a href="https://www.canada.ca/en/news/advanced-news-search/news-results.html">Access all news products</a>.</p>
Please remove the extra dot at the end of "Access all news products" since it's not part of the BR.

2025-02-03 14:43 UTC, duboisp approved these changes
Look good.

2025-02-04 14:57 UTC, Ricokola approved these changes
Seems completed and good to go!

2025-02-04 15:32 UTC, merged