Contributors: move to sites, change context of use
wet-boew/GCWeb pull request #2459
Opened 2024-12-23 19:03 UTC by Garneauma

- Moved Cotnributors component to Sites section
- Updated Page details component to include Contributors component
- Updated Topic template with new Contributors location

Related to WET-505

2025-01-14 16:54 UTC, duboisp requested changes
Todo:
* Centralize sample inside the contributor component.
* (Optional) remove the "gc-" prefix in the file/folder name for the contributor component
* Update the contributor component documentation to add more emphasis on the breaking change + migration instruction.
* Page details - move demoted pattern in demoted folder
* For "contributor" component, make it a minor version for now (v1.1) because both are still ok, but identify the version 1.0 as demoted. We will increase the major version when we will switch the v1.0 from "demoted" into "deprecated" state.

This change is:
* Minor change for contributor component - Add new pattern where located in the page details section
* Minor change for page details component - Add new pattern that include the contributor component
* Minor change for Topic template - Add new pattern that include the new page details with the contributor component
* Minor change for the "Topic" template - Add new pattern that implement page-details v 3.3 where the contributor component are in the page-details section
* We will perform a major change to those component, when we will switch them from "demoted" into "deprecated" at our next major release

2025-01-14 16:54 UTC, duboisp commented on sites/page-details/index.json-ld
Need one additional implementation instruction: Migration from 3.2 (demoted) to 3.3 (stable)

2025-01-14 16:54 UTC, duboisp commented on sites/gc-contributors/includes/gc-contributors.html
> +	<h2>{% if page.language == "en" %}From:{% else %}De&nbsp;:{% endif %}</h2>
Because it is now inside the page details section, this heading must be downgraded for an heading level 3 (`<h3>`)

2025-01-14 16:54 UTC, duboisp commented on sites/page-details/index.json-ld
>  			"name": "Page details - version 3.2",
Need to update the status for 3.2

```suggestion
			"name": "Page details - version 3.2",
			"status": "demoted",
```

2025-01-14 16:54 UTC, duboisp commented on sites/page-details/deprecated/page-details-v3.2-en.html
> +	"title": "Content page including complete page details version 3.2 (deprecated)",
```suggestion
	"title": "Content page including complete page details version 3.2 (demoted)",
```

2025-01-14 16:54 UTC, duboisp commented on templates/topic/deprecated/topic-stackedheader_v2-en.html
Move to "demoted" and identify in the docs as "demoted"

2025-01-14 16:54 UTC, duboisp commented on templates/topic/deprecated/topic-stackedheader_v2-fr.html
Move to "demoted" and identify in the docs as "demoted"

2025-01-14 16:54 UTC, duboisp commented on templates/topic/deprecated/topic_v2-en.html
Move to "demoted" and identify in the docs as "demoted"

2025-01-14 16:54 UTC, duboisp commented on templates/topic/deprecated/topic_v2-fr.html
Move to "demoted" and identify in the docs as "demoted"

2025-01-14 16:54 UTC, duboisp commented on templates/topic/index.json-ld
> +	"version": "3.0",
Set a minor version for now (v2.2) as we do allow both pattern for now, but demote the version 2.1

2025-01-14 16:54 UTC, duboisp commented on templates/topic/index.json-ld
Need implementation with migration instruction from version 2.0 (demoted) to v2.1 (stable)

2025-01-14 16:54 UTC, duboisp commented on templates/topic/index.json-ld
> +			"iteration": "_:iteration_topic_4",
For this one, add an instruction note that mention about the "Contributor" component that are located in the "page details" configuration

2025-01-29 16:24 UTC, Garneauma commented on _includes/sites/gc-contributors/gc-contributors.html
@duboisp IMO this is not a sample. This is an include since it has logic in it (leverages the "page.contributors" property.

2025-01-29 18:39 UTC, Garneauma commented on sites/page-details/deprecated/page-details-v3.2-en.html
> +{% include page-details/footer-3.2.html %}
@duboisp The same code snippet is used in the index.json-ld for documentation. Instead of having a duplication, it is centralized in an include file.

2025-01-29 18:40 UTC, Garneauma commented on sites/page-details/deprecated/page-details-v3.2-fr.html
> +{% include page-details/footer-3.2.html %}
@duboisp See my comment in the same comment for the English version.

2025-02-07 20:28 UTC, duboisp requested changes
I reviewed and tested locally all modified files. Its look good. There is a few inline comment to address and the following change to do:

Can you add a temporary redirect for the following files? This is to avoid broken link from the guidance material. Add a comment that those redirect can be removed in a year or two from now.
* /components/gc-contributors/gc-contributors-doc-en.html
* /components/gc-contributors/gc-contributors-doc-fr.html
* /components/gc-contributors/gc-contributors-en.html
* /components/gc-contributors/gc-contributors-fr.html

Once that completed, I will be able to approve this PR. 

Note: This PR does impact:
* Minor - Contributor
* Minor - Page details
* Minor - Topic template

2025-02-07 20:28 UTC, duboisp commented on sites/page-details/includes/footer-3.2.html
Is that include file are still needed considering you added the code statically in the demote example?

2025-02-19 14:06 UTC, duboisp approved these changes
Reviewed and looks good.

2025-02-19 14:25 UTC, duboisp approved these changes
Me and @Garneauma reviewed the change required to fix the merge conflict, the merged conflict are resolved and should work as expected

2025-02-20 13:46 UTC, merged